Feat/#145 auth
hufscheer/spectator-server pull request #150
Opened 2024-06-11 15:39 UTC by Jin409

## 🌍 이슈 번호

## 📝 구현 내용

## 🍀 확인해야 할 부분

2024-06-22 05:46 UTC, ldk980130 requested changes
인증/인가 구현하느라 진자 수고하셨습니다! 테스트 코드 꼼꼼하게 짜여진거에 감동... 그 외 자잘한(?) 리뷰들 남겼으니 확인해주세요.

전체적인 구조는 좋다고 생각합니다 👍

2024-06-22 05:46 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/application/AuthService.java
> +    public JwtResponse managerLogin(final LoginVO loginVO) {
1. 자바 컨벤션 상 메서드 이름은 되도록 동사로 시작하도록 구성해주면 좋을 것 같습니다!
2. dto 네이밍 컨벤션이 지금까지는 XXRequest로 써오고 있었기에 이부분 통일하면 좋을 것 같아요

2024-06-22 05:46 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/application/AuthService.java
> +            throw new NotFoundException(AuthorizationErrorMessages.MEMBER_NOT_FOUND_EXCEPTION);
null을 다룰 땐 Java Optional을 사용하는게 좋을 것 같습니다!

Optional을 이용한 메서드 체이닝을 사용하면 코드가 더 깔끔해질 것 같아요.
``` java
Member member = memberRepository.findByEmail(loginVO.email())
                .filter(m -> passwordEncoder.matches(loginVO.password(), m.getPassword()))
                .filter(Member::isManager)
                .orElseThrow();
```

2024-06-22 05:46 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +        Cookie cookie = CookieUtil.getCookie(request, COOKIE_NAME).orElse(null);
Optional을 사용하는데 orElse(null)을 하면 Optional을 사용하는 이유가 없어집니다. null을 안전하게 다루는 것이 아닌 그대로 다시 노출시켜 버리니까요.

Optinal의 ifPresent를 사용하면 값이 있는 경우에만 로직을 실행시킬 수 있어요.

``` java
    protected void doFilterInternal2(HttpServletRequest request, HttpServletResponse response, FilterChain chain)
            throws IOException, ServletException {
        CookieUtil.getCookie(request, COOKIE_NAME)
                .ifPresent(cookie -> {
                    Authentication authentication = jwtProvider.getAuthentication(cookie.getValue());
                    SecurityContextHolder.getContext().setAuthentication(authentication);
                });
        
        chain.doFilter(request, response);
    }
```

2024-06-22 05:46 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +    }
이 로직 꼭 필요한가요? 인증을 허용하는 url을 관리하는 곳이 두 곳이 되어버려요. (securityconfig와 여기)

제 기억엔 이런 로직 필요 없었는데 없애도 괜찮지 않을까요? 테스트는 통과합니다.

2024-06-22 05:46 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/jwt/JwtProvider.java
> +        }
토큰을 사용하는 이유는 'stateless' 때문입니다. 매 로그인 시 세션 저장소를 뒤지지 않아도 토큰이 유효한지만 검증하면 되기 때문이에요.

그런데 지금 방식은 로그인한 사용자가 매번 서버에 요청할 때마다 DB를 찾고 있어요. 이는 세션 저장소를 찾는 것보다 더 무거운 작업입니다.

토큰이 유효한지만 검증하면 어떨까요? 유효한 토큰이라는 것은 우리가 검증한 사용자이기 때문에 db에 해당 유저가 있는지는 필요 없다고 생각해요.

이후 로직에서 Member가 필요할 때만 조회를 하고, 그 때 혹시 Member가 사라져 있다면 그 때 예외를 발생시켜도 될 것 같습니다.

2024-06-22 05:46 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/presentation/AuthController.java
> +    private String COOKIE_NAME;
엑세스 토큰에 필요한 쿠키 이름을 yml로 관리하는 건 좋은 것 같아요. prod.yml 환경에서의 쿠키 이름을 다르게 한다면 보안이 더 좋아질 수도 있겠네요. 👍 배포하기 전에 be-config 저장소에 추가한 yml 설정 추가하는 거 잊지 마세요~

2024-06-22 05:46 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/presentation/AuthController.java
> +    }
이 두 api는 왜 필요한 걸까요? 👀  테스트에서만 사용하는 거라면 test 모듈로 옮겨주세요

2024-06-22 05:46 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/utils/CookieUtil.java
> +    }
한 줄에 `.`은 하나씩 찍는게 가독성이 더 좋습니다.
``` java
return ResponseCookie.from(nameOfCookie, token)
                .path("/")
                .sameSite("Strict")
                .secure(true)
                .maxAge(Math.toIntExact(cookieValidTime))
                .httpOnly(true)
                .build();
```

2024-06-22 05:46 UTC, ldk980130 commented on src/main/java/com/sports/server/command/member/domain/Member.java
> +    }
롬복을 쓰고 있어서 이건 없어도 될것 같아요

2024-06-22 05:46 UTC, ldk980130 commented on src/test/java/com/sports/server/auth/application/AuthServiceTest.java
> +public class AuthServiceTest extends ServiceTest {
로그인이 실패하는 시나리오만 있는데 로그인이 성공하는 시나리오의 테스트도 필요할 것 같습니다!

2024-06-22 06:54 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/application/AuthService.java
> +        memberRepository.save(new Member(email, passwordEncoder.encode("1234"), true));
여기는 왜 ``"1234"``로 하드코딩되어 있는 거야?

2024-06-22 07:10 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/application/AuthService.java
> +        memberRepository.save(new Member(email, passwordEncoder.encode("1234"), true));
그리고 클래스 레벨에 ``@Transactional(readOnly = true)`` 되어 있는데 그러면 위의 save 메서드는 제대로 동작하지 못할거 같아.

2024-06-22 07:19 UTC, fingersdanny commented on src/main/java/com/sports/server/command/member/domain/MemberRepository.java
> +    Member findMemberByEmail(final String email);
interface 내부의 메서드 인자를 final로 선언하는건 사실 구현체에 아무런 영향을 끼칠 수 없어서 불필요하다고 생각해

이 [링크](https://www.artificialworlds.net/blog/2014/04/02/using-the-final-keyword-in-interface-method-parameters-does-nothing/)에서 설명하고 있듯이 실제 구현체에서 final로 하게끔 강제할 수 없는거 같아

2024-06-22 07:22 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/presentation/AuthController.java
``manager``라는 prefix를 붙일꺼면 Class level에 ``@RequestMapping("/manager")``로 해도 괜찮지 않을까?

2024-06-22 07:31 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/details/MemberDetails.java
> +        authorities.add(new SimpleGrantedAuthority("user"));
이건 한번 얘기 해봐야할거 같긴 한데 이전에 회의에서 우리가 추후에 사용자 로그인 (매니저 말고 그냥 사용자)를 추가할 수도 있다고 했던 기억이 있어.

사실 위와 같은 경우라면 Member가 권한을 들고 있는 형태로 바뀌거나 아니면 지금처럼 isManager를 확인해서 권한을 쥐어줘야 한다고 생각해.

따라서 위와 같은 경우에서는
```suggestion
        authorities.add(new SimpleGrantedAuthority("MANAGER"));
```

로 해야하지 않을까?

그리고 보통은 나는 Security 구현할때 권한을 아래와 같이 Enum Type으로 만들어 쓰는데 그러면 대문자로,, 권한을 주거든

```java
public enum AuthorityType {
    MANAGER,
    USER
}
```
그래서 대문자로 해야하지 않을까? 라는 생각도 있어

2024-06-22 08:12 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +    }
나는 오히려 이걸 유지하고 위의 cookie 가 null 일때 예외를 던져야하지 않을까 라는 생각이 있는데

지금 구현 방법에서 이게 없으면 아래와 같은 이유로 로그인이 안되지 않을까?

OncePerRequestFilter의 shouldNotFilter에 대한 기본 구현이 false를 반환하는데

false일때 모든 요청을 이 필터를 거치게 되어 있고 따라서 거치지 않게 하기 위해서 위처럼 구현한듯..?

그래서 아래 세가지 경우에 있어서

```markdown
1. 매니저가 로그인을 시도한다 -> true (필터를 거치지 않고 액세스 토큰을 받아옴)
2. 매니저 로그인이 필요한 경로에 접근을 시도한다 -> false (필터를 무조건 거치게 해서 SecurityContextHolder에 권한을 추가해야함)
3. 기존 관객서버 API에 대한 요청이다 -> true (필터를 거치지 않아도 됨)
```

2024-06-22 08:16 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +        Cookie cookie = CookieUtil.getCookie(request, COOKIE_NAME).orElse(null);
여기에 ``OrElseThrow``를 추가하면 될듯..?

    protected void doFilterInternal2(HttpServletRequest request, HttpServletResponse response, FilterChain chain)
            throws IOException, ServletException {
        CookieUtil.getCookie(request, COOKIE_NAME)
                .ifPresent(cookie -> {
                    Authentication authentication = jwtProvider.getAuthentication(cookie.getValue());
                    SecurityContextHolder.getContext().setAuthentication(authentication);
                })
                .orElseThrow(() -> new UnauthorizedException(AuthorizationErrorMessage.INVALID_AUTHORITY));
        
        chain.doFilter(request, response);
    }

2024-06-22 08:19 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/jwt/JwtProvider.java
> +        Date now = new Date();
LocalDateTime 대신 이걸 사용한 이유가 있을까?

2024-06-22 08:25 UTC, fingersdanny commented on src/test/java/com/sports/server/auth/acceptance/AuthAcceptanceTest.java
아래 두 가지에 대한 테스트가 필요할거 같아
```markdown
1. 로그인 실패 시 제대로된 메세지가 담긴 예외 응답이 오는지
2. 기존 관객서버에 대한 접근이 제대로 되는지..?
```

2024-06-22 08:28 UTC, fingersdanny commented on src/test/java/com/sports/server/support/TestSecurityConfig.java
아예 TestSecurityConfig를 만들어서 csrf를 해결한건 정말 잘한거 같아 💯

2024-06-22 08:34 UTC, fingersdanny requested changes
인증, 인가 구현한다고 고생 많았어! 코멘트에 남긴 리뷰 확인 부탁하고

난 개인적으로 둘 다 쿠키에 있어도 상관없다고 생각하고
``MemberDetails``의 특성상 Dto에 가깝긴 한데 진짜 Dto는 아니라고 생각할 수도 있으니까 details에 두고 싶으면 상관없다고 생각해.

개인적으로는 dto가 있으면 dto package에 두려고 하는 듯

2024-06-22 15:40 UTC, Jin409 commented on src/main/java/com/sports/server/auth/application/AuthService.java
> +        memberRepository.save(new Member(email, passwordEncoder.encode("1234"), true));
이거 테스트하려고 넣어뒀던거라 삭제할게!

2024-06-22 16:17 UTC, Jin409 commented on src/main/java/com/sports/server/auth/presentation/AuthController.java
> +    }
포스트맨으로 요청 보내보려고 짜뒀던 거라서 삭제할게요!!

2024-06-22 16:19 UTC, Jin409 commented on src/main/java/com/sports/server/command/member/domain/Member.java
> +    }
@getter 를 이용해서 모든 필드를 열어두지 않고, 인증 인가 과정에서 필요한 email 이랑 password 만 열어두려고 직접 구현했는데 어떻게 생각하시는지 궁금합니당

2024-06-22 16:20 UTC, Jin409 commented on src/main/java/com/sports/server/command/member/domain/MemberRepository.java
> +    Member findMemberByEmail(final String email);
헉 그렇군 몰랐어.. 감사합니땅

2024-06-22 16:21 UTC, Jin409 commented on src/main/java/com/sports/server/auth/presentation/AuthController.java
테스트로 불필요한 메서드들을 적어뒀던거라 메서드가 다시 한개가 되었기에.. 일단 이건 보류해둘게!

2024-06-22 16:25 UTC, Jin409 commented on src/main/java/com/sports/server/auth/jwt/JwtProvider.java
> +        Date now = new Date();
딱히 특별한 이유는 없었는데 찾아보니 LocalDateTime 이 더 좋겠넹.. 이거 수정할게!

2024-06-23 13:15 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +    }
로그인이 필요 없는 url인 경우에는 시큐리티가 이 필터 자체를 작동 안시키지 않나? 애초에 지금까지 시큐리티 사용하면서 로그인이 필요한 url, 필요 없는 url을 이렇게 두 곳에서 관리한 적이 없어서 말이지.

2024-06-23 13:19 UTC, ldk980130 commented on src/main/java/com/sports/server/command/member/domain/Member.java
> +    }
개인적인 생각으론 롬복 게터를 써서 코드가 깔끔해지는걸 더 좋아하긴 해요. 다른 엔티티들도 애초에 게터를 다 열어놓고 있어서 통일시키면 좋을 것 같기도 하고요.

2024-06-23 14:17 UTC, Jin409 commented on src/main/java/com/sports/server/command/member/domain/Member.java
> +    }
넵! 그렇게 반영할게요

2024-06-23 14:21 UTC, Jin409 commented on src/main/java/com/sports/server/auth/jwt/JwtProvider.java
> +        Date now = new Date();
바로 아래 코드에서 액세스 토큰을 생성할 때 .withExpiresAt() 에서 받는 인자 타입이 Date 여서 그렇게 했어!

2024-06-23 18:41 UTC, Jin409 commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +    }
나도 명확한 원인은 더 해봐야 알 것 같은데, 테스트에서는 shouldNotFilter 를 주석 처리해도 다 통과가 돼. 
그런데 포스트맨으로 실제 요청을 보내보면 해당 필터가 동작해서 예외를 던져.. 병룡오빠가 말한 것처럼 OncePerRequestFilter의 shouldNotFilter에 대한 기본 구현이 false 를 반환해서 필터가 동작해버려서 직접 명시한 거였어.

2024-06-24 15:03 UTC, Jin409 commented on src/main/java/com/sports/server/auth/jwt/JwtProvider.java
> +        }
해당 부분 구현해뒀습니다!
현재 1. AuthorizationFilter 에서는 임시로 Authentication 객체를 등록해두고 2. AuthenticationAspect 를 작성해 컨트롤러 단에서 해당 어노테이션을 붙이면 쿠키의 액세스 토큰을 꺼내와서 Member 객체를 argument로 등록하게 해뒀습니당.
그런데 고민되는 부분이, 사실상 시큐리티의 필터가 동작하면서 /manager 가 붙은 엔드포인트들은 모두 쿠키와 액세스 토큰을 검증해요. 그런데 AuthenticationAspect 에서도 쿠키의 액세스 토큰을 꺼내와야 하다보니, 한번 더 검증이 이루어지게 되는데 중복적으로 이루어지다보니 이 부분을 어떻게 하면 좋을지 고민이 됩니답..

2024-06-24 15:09 UTC, Jin409 commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +                            jwtProvider.validateToken(cookie.getValue());
매번 DB 를 뒤지는 것은 stateless 하지 못하다는 피드백을 바탕으로 수정했습니다!

## 수정한 부분들
- AuthorizationFilter 에서 임시로 Authentication 객체를 context 에 등록하도록 수정했습니다. (아무 Authentication 객체도 없으면 401 에러가 발생)
- JwtProvider 에서 getAuthentication 메서드 삭제
- JwtProvider 에 토큰의 유효성 검증 메서드 추가
   - 성격이 바뀌었다고 판단해 JwtProvider >> JwtUtil 로 클래스명 변경
- AuthenticationAspect 클래스 추가 >> 어노테이션으로 Member 객체를 찾을 수 있도록

## 논의 사항
현재 1. AuthorizationFilter 에서는 임시로 Authentication 객체를 등록해두고 2. AuthenticationAspect 를 작성해 컨트롤러 단에서 해당 어노테이션을 붙이면 쿠키의 액세스 토큰을 꺼내와서 Member 객체를 argument로 등록하게 해뒀습니당.

그런데 고민되는 부분이, 사실상 시큐리티의 필터가 동작하면서 /manager 가 붙은 엔드포인트들은 모두 쿠키와 액세스 토큰을 검증해요. 그런데 AuthenticationAspect 에서도 쿠키의 액세스 토큰을 꺼내와야 하다보니, 한번 더 검증이 이루어지게 되는데 중복적으로 이루어지다보니 이 부분을 어떻게 하면 좋을지 고민이 됩니답..

2024-06-24 22:22 UTC, Jin409 commented on src/main/java/com/sports/server/auth/details/MemberDetails.java
> +        authorities.add(new SimpleGrantedAuthority("user"));
아직은 사용자 로그인을 구현하는 것에 대해 자세한 논의가 이뤄지지 않아서 AuthorityType 과 같이 권한과 관련된 ENUM 은 추가하지 않고 user 에서 MANAGER 로만 수정해서 반영했어!

2024-06-24 22:36 UTC, Jin409 commented on src/test/java/com/sports/server/auth/acceptance/AuthAcceptanceTest.java
`2. 기존 관객서버 API에 대한 접근이 제대로 되는지` 에 대해서는 어떻게 테스트 하는 게 좋을 것 같아?
나는 현재 시큐리티 필터가 동작하고 있지만, 다른 테스트들이 모두 통과한다는 점에서 굳이 이 부분을 테스트로 넣지 않았거든..!

2024-06-25 04:09 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +                            MemberDetails memberDetails = new MemberDetails(new Member("temp", "temp"));
토큰 안에 memberId는 없나요? 이런 임시 객체럴 설정할게 아니라 MemberDetail에 memberId를 넣어두고, 이후 비즈니스 로직에서 쓰면 될 것 같은데

2024-06-25 04:12 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +                            jwtProvider.validateToken(cookie.getValue());
임시 등록은 필요 없을 것 같아요. 아래 코멘트에도 남겼는데 토큰이 유효하다면 `MemberDetail`에는 토큰에서 추출한 `memberId`를 세팅하면 됩니다. 이후 비즈니스 로직에선 토큰을 신경쓸 필요도 없이 Authentication 내부의 memberId로 비즈니스 로직을 처리하면 될 것 같아요.

2024-06-25 04:20 UTC, ldk980130 requested changes
인증/인가가 급한건 아니니까 논의를 충분히 한뒤 머지해도 될 것 같은데 어떨까요? 리뷰가 길어질 것 같아서 말이죠..ㅎㅎ

2024-06-25 04:20 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/utils/CookieUtil.java
> +    }
해당 이름의 쿠키가 없으면 예외를 던지고 `Optional.empty`를 반환하지 않기 때문에 반환 타입을 `Optional`로 하지 않아도 될 것 같아요. 쿠키가 없는 상황을 명확한 예외로 간주한다면 말이죠.

없어도 되고 없으면 `Optional.empty`를 반환한다는 정책이라면 예외를 던질게 아니라 empty를 반환하면 될 것 같습니다.

그리고 이름 또한 토큰에 관련된 쿠키를 꺼낸다는 역할로만 제한할거면 `getCookie`가 아니라 인증에 관련된 이름이었으면 좋겠어요. 왜냐하면 예외는 토큰 관련 예외를 던지고 있기 때문이에요.

2024-06-25 04:20 UTC, ldk980130 commented on src/main/java/com/sports/server/command/member/domain/Member.java
> +        this.isManager = true;
1. 이메일과 비밀번호 검증을 없앤 이유가 있나요?
2. Member 중 Manager를 생성한다는건 나름 중요한 비즈니스 정책 같아요. 밖에서 이걸 사용할 때 new Member를 했는데 매니저를 생성하는건 의도하지 않는 상황일 수도 있어요. `Member.manager(...)`와 같은 정적 팩터리 메서드를 사용하면 어떨까요?

2024-06-25 04:20 UTC, ldk980130 commented on src/test/java/com/sports/server/auth/jwt/JwtUtilTest.java
> +}
왜 주석처리 된걸까요?

2024-06-25 15:25 UTC, fingersdanny reviewed
리뷰 코멘트 확인 부탁할게

2024-06-25 15:25 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/application/AuthService.java
로그인 처리를 ``UserDetailsService``를 구현해서 처리했다면 [여기](https://sol-devlog.tistory.com/3)에 나온 방법으로 했을 수도 있을거 같아.

2024-06-25 15:25 UTC, fingersdanny commented on src/main/java/com/sports/server/command/member/domain/Member.java
> +        this.isManager = true;
여기에 더해서 boolean type인 ``isManager``를 지우고 권한 칼럼을 추가하는건 어떨까..?

2024-06-25 15:25 UTC, fingersdanny commented on src/test/java/com/sports/server/auth/aop/AuthenticationAspectTest.java
> +        assertEquals(AuthorizationErrorMessages.MEMBER_NOT_FOUND_EXCEPTION, exception.getMessage());
``assertThatThrownBy()`` 메서드로 예외 테스트를 한줄로 줄일 수 있을 거 같아.

```suggestion
    assertThatThrownBy(
        () -> authenticationAspect.authenticate(proceedingJoinPoint, null)
    ).isInstanceOf(UnauthorizedException.class)
    .hasMesssage(AuthorizationErrorMessages.MEMBER_NOT_FOUND_EXCEPTION);
```

2024-06-25 19:11 UTC, Jin409 commented on src/test/java/com/sports/server/auth/jwt/JwtUtilTest.java
> +}
이전 코드 남겨놓고 안지웠다..!

2024-06-27 14:08 UTC, Jin409 commented on src/main/java/com/sports/server/auth/dto/JwtResponse.java
좋은 것 같아! 이거 수정해둘게

2024-06-27 14:51 UTC, Jin409 commented on src/main/java/com/sports/server/auth/utils/CookieUtil.java
> +    }
@ldk980130 아예 cookieUtil 클래스 자체 내에서 권한과 관련된 예외는 처리하지 않도록 하는 게 맞을 것 같아서 수정했어요!

2024-06-27 14:57 UTC, Jin409 commented on src/main/java/com/sports/server/command/member/domain/Member.java
> +        this.isManager = true;
@ldk980130 

1. 회원가입 로직이 없어서 안쓰이는데 남아있어서 지웠어요..! + 정책적으로 논의가 없는데 임의로 제가 짰던 코드라 레거시 같기도 해서 지웠슴니다. 그래도 있는게 나으려나요?
2. 조습니다!

2024-06-27 14:57 UTC, Jin409 commented on src/main/java/com/sports/server/command/member/domain/Member.java
> +        this.isManager = true;
@fingersdanny 
권한이 일반 사용자 (관객) 랑 매니저 말고도 추가될 일이 있으려나?!

2024-07-04 11:42 UTC, fingersdanny reviewed
리뷰 반영하느라 고생했어!

2024-07-04 11:42 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/config/SecurityConfig.java
> +    AuthenticationEntryPoint authEntryPoint;
필드 주입을 사용한 특별한 이유가 있을까??

2024-07-05 16:02 UTC, fingersdanny approved these changes

2024-07-06 13:23 UTC, merged