[FEAT] 라인업 변경 사항 반영
hufscheer/spectator-server pull request #153
Opened 2024-06-15 10:02 UTC by fingersdanny

## 🌍 이슈 번호
* closed #151

## 📝 구현 내용
* 라인업선수가 선발인지 후보인지 확인할 수 있도록 로직 변경
* 생성되는 라인업 선수의 기본 값은 후보이고 추후 확장성을 위해 Enum Type으로 관리, 변수명은 ``state``
* ``GameQueryController`` 라인업 선수를 포함하는 응답에 선수 ID와 선수 상태 포함하도록 추가
* ``LineupController`` 라인업 선수의 상태를 변경하는 API 추가
* 해당 API 연관 문서화, 인수, 서비스 테스트 작성 및 테스트 완료

## 🍀 확인해야 할 부분
* 이번에 작성하면서 보니까 DTO 유효성 검증하는 부분들이 정상적으로 되지 않는 부분들이 있는거 같은데 한번 얘기 해보면 좋을거 같아
* 일단 API를 어디에 붙여야할지 모르겠어서 ``LineupController``를 만들고 개별적으로 두었는데 ``GameController``와 통합하는게 좋을까?
* 이번 백엔드 회의 때``Controller`` 클래스들의 컨벤션에 대해서 좀 얘기해봐야할거같아

2024-06-15 11:42 UTC, ldk980130 requested changes

2024-06-15 11:42 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
도메인의 상태 변경은 도메인 로직에게 맡기면 어떨까? ORM을 쓰고 있으니까 말이야. 도메인의 특화된 메서드로 상태 변경을 하고 내부 상태를 캡슐화하는게 좋을 것 같아!

``` java
lineupPlayer.addToStarting() // 선발 상태로 변경

lineupPlayer.removeFromStarting // 후보 상태로 변경
```

메서드 이름을 달라질 수도 있지만 이런식으로 로직을 짜면 어떨까?

아마 응원 횟수 갱신 로직을 보고 비슷하게 한 것 같은데 그 로직은 동시성 문제 때문에 그런 식으로 짰던거라 나중에 한 번 얘기해 보면 좋을 것 같아

2024-06-15 11:42 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/presentation/LineupPlayerController.java
> +}
1. PutMappging은 해당 리소스 전체를 대체하거나 변경할 때 사용한다고 알고 있어서 PostMapping 외에 사용할 거면 PatchMapping을 사용하면 어떨까?
2. api도 state를 받아서 해당 state로 변경하는 것 보다 명확히 두 api로 나누면 어떨까? 특정 선수를 선발로 변경하는 api와 후보로 내리는 api로 말이야. api 레벨에서부터 엔티티 내부를 캡슐화하면 좋을 것 같아.
  a. `/lineup-players/{lineupPlayerId}/add-starting`
  b.  `/lineup-players/{lineupPlayerId}/remove-starting`

2024-06-16 18:00 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
동규오빠 의견 좋아! 그런데 그렇게 되려면 다 양방향 참조를 해야 할 것 같은데 이 pr 에서 그걸 다 처리하는 게 맞을까 하는 생각도 드네 ....!

2024-06-16 18:01 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/presentation/LineupPlayerController.java
> +}
나도 PatchMapping 쓰는거 찬성 ~!!

2024-06-20 07:22 UTC, fingersdanny commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
이거에 대한 고민이 있었는데 일단 응원 횟수 갱신 로직을 보고 구현 한거긴 해. 

그럼 저 API를 호출하면 라인업 선수 상태 변경 뿐만 아니라 게임에 선발이 등록되어야 한다고 생각하는걸까?

@ldk980130

2024-06-20 11:59 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
이 api를 호출한다는건 이미 lineupPlayer가 GameTeam에 등록되어 있고 기본값은 '후보'상태이기에 Game을 만들었다면 모든 lineupPlayer가 '후보' 상태로 등록되어 있을 거야.

이 api들은 그 상태에서 각 선수들을 '선발'로 올리거나 '후보'로 되돌리는 기능을 한다고 생각해.

'라인업 선수 상태 변경'이 곧 '선발로 올림' 또는 '후보로 내림'이라고 생각해서 결국 상태 변경만 담당하게 될 것 같아!

2024-06-25 16:54 UTC, fingersdanny commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
이거 리뷰 보고 다시 작업 중인데 혹시 양방향 관계 설정이 내가 이해한게 맞나 봐줄래?

* Game에 LineupPlayer 리스트 추가
* GameTeam에 LineupPlayer 리스트 추가
* LineupPlayer에 선발 혹은 후보 상태로 만드는 메서드 추가

2024-06-26 18:02 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
나는 game, gameTeam 서로 양방향 참조이고 gameTeam, lineupPlayer 서로 양방향 참조라고 이해했는데 아니려나?

2024-06-26 18:09 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
LineupPlayer 랑 GameTeam 은 양방향 참조 안해도 되지 않을까?

Game 에 LineupPlayer 가 있으니까 바로 상태를 바꾸면 되지 않으려나?

2024-06-27 08:52 UTC, fingersdanny commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
> LineupPlayer 랑 GameTeam 은 양방향 참조 안해도 되지 않을까?
> 
> Game 에 LineupPlayer 가 있으니까 바로 상태를 바꾸면 되지 않으려나?

내가 너무 늦게 봐버렸네... 일단 바꿔보긴 했는데 한번 리뷰 받고 다시 올려볼게 그럼

2024-06-27 13:37 UTC, ldk980130 approved these changes
수고했어! 조금 더 생각해볼만한 점 리뷰 달았어. 너무 생산성이 안나오는 것 같아서 일단 approve를 하는데 아래 사항에 대해선 더 고민해보면 좋을 것 같아

1. 객체에게 메시지를 던지도록 구현하기
2. 단위 테스트 작성

우리가 도메인 중심으로 로직을 짜고 비즈니스 로직을 도메인으로 밀어넣다보면 스프링 없는 순수 자바로 구성되는 단위 테스트를 할 수 있게 돼. 사실 테스트는 도메인 단위 테스트의 개수가 제일 많아야 하는데 우리가 지금까진 조회 위주의 기능을 짜다보니 짤 기회가 많이 없었어.

앞으로는 도메인에 최대한 비즈니스 로직을 밀어넣고, 그걸 기반으로 단위 테스트를 많이 짜보면 좋을 것 같아!

2024-06-27 13:37 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
@Jin409 
반대 아닌가? Game에 LineupPlayer가 없고 GameTeam에 LineupPlayer 리스트가 존재하면 되는거 아닌가? 나는 지금 구조 좋다고 생각해!

객체가 객체에게 메시지를 전달할 때 이 방향으로 가면 좋을 것 같음!
Game -> GameTeam -> LineupPlayer

2024-06-27 13:37 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/domain/GameTeam.java
> +				}
이 로직은 LineupPlayer에게 맡기면 stream 로직이 더 깔끔해질 것 같아!

``` java
    public void changeStateToStarter() {
        if (this.state == STARTER) {
            throw new CustomException(HttpStatus.BAD_REQUEST, "이미 선발로 등록된 선수입니다.");
        }
        this.state = LineupPlayerState.STARTER;
    }
```

덧붙여서 비즈니스로직을 짤 땐 getter를 지양하고 객체에게 메시지를 전달하는 방식으로 구현하면 좋을 것 같아.
https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/

2024-06-27 14:05 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayerRepository.java
> +}
아하 나는 Game에 LineupPlayer 리스트를 추가한다고 해서 그렇게 생각했던 건데..!
지금 Game 은 LineupPlayer 리스트 추가 안한 것 같은데 맞지?

2024-06-28 16:11 UTC, ldk980130 approved these changes
확인 완료!

2024-07-01 03:12 UTC, merged