Feat/#163 leagueteam
hufscheer/spectator-server pull request #165
Opened 2024-07-17 17:23 UTC by Jin409

## 🌍 이슈 번호

## 📝 구현 내용

## 🍀 확인해야 할 부분

2024-07-23 14:34 UTC, ldk980130 requested changes

2024-07-23 14:34 UTC, ldk980130 commented on src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
> +            Pattern.compile("/leagues/\\d+/teams/\\d+/delete-logo"), "POST"
제 PR이 머지되면 반영해서 제거해주세요~

2024-07-23 14:34 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        leagueTeamRepository.save(leagueTeam);
이렇게 코드가 다다다닥 붙어 있으면 읽을 때 바로 안읽히는 면이 있는 것 같지 않아?

이건 내가 최근에 시작한 코드 정리 방법인데 관련 있는 코드끼리 뭉쳐서 줄바꿈을 하면서 코드를 쓰면 읽기 훨씬 편하더라고.

``` java
    public void register(final Long leagueId, final Member manager, final LeagueTeamRequest.Register request) {
        League league = getLeagueAndCheckPermission(leagueId, manager);

        String imgUrl = changeLogoImageUrlToBeSaved(request.logoImageUrl());
        LeagueTeam leagueTeam = request.toEntity(manager, league, imgUrl);

        for (LeagueTeamPlayerRequest.Register player : request.players()) {
            leagueTeam.addPlayer(player.toEntity(leagueTeam)); // 중요한 도메인 로직은 이렇게 강조하는 것도 좋은 방법일 듯? 이건 스타일 차이
        }
        
        leagueTeamRepository.save(leagueTeam);
    }
```

2024-07-23 14:34 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +    }
이거랑 다른 메서드들도 마찬가지! 협업을 하면 다른 사람 코드를 읽을 때가 너무 많은데 코드 배치도 한 번 신경쓰면 어떨까?

2024-07-23 14:34 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +    }
만약 s3에서 이미지파일을 삭제했는데 이 트랜잭션이 실패하면 어떻게 될까? 👀 트랜잭션이 실패하면 이미지 파일도 지우면 안될텐데 어떻게 해결할 수 있을까?

2024-07-23 14:34 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamRepository.java
> +                    + "WHERE lt.id = :id"
원래 왜 영속화가 안됐는지는 잘은 모르겠지만 페치조인하는거 자체는 괜찮아 보입니당

2024-07-23 14:34 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/dto/LeagueTeamRequest.java
> +            return new LeagueTeam(name, logoImageUrl, manager, manager.getOrganization(), league);
manager와 organization을 함께 받기 보단 manager만 넣어주고 내부에서 manager.getOrganization을 부르면 생성자가 짧아져서 좋을 것 같아!

2024-07-23 14:34 UTC, ldk980130 commented on src/main/java/com/sports/server/common/application/S3Service.java
> +            throw new CustomException(HttpStatus.BAD_REQUEST, "이미지 파일 삭제에 실패했습니다.");
여기서 이미지 업로드가 실패하는건 BAD_REQUEST (클라이언트 잘못)이 아니라 서버 잘못 (INTERNAL SERVER ERROR)가 아닐까?

2024-07-23 22:26 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/dto/LeagueTeamRequest.java
> +            return new LeagueTeam(name, logoImageUrl, manager, manager.getOrganization(), league);
좋아! 반영할게

2024-07-23 22:26 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/dto/LeagueTeamRequest.java
> +            return new LeagueTeam(name, logoImageUrl, manager, manager.getOrganization(), league);
좋아! 반영할게

2024-07-23 22:29 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        leagueTeamRepository.save(leagueTeam);
오호 좋은 것 같아! for 문도 이게 더 가독성이 좋은 것 같당

2024-07-23 22:35 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +    }
생각도 못한 부분인데 감사합니땅 한번 고쳐볼게!

2024-07-23 22:35 UTC, Jin409 commented on src/main/java/com/sports/server/common/application/S3Service.java
> +            throw new CustomException(HttpStatus.BAD_REQUEST, "이미지 파일 삭제에 실패했습니다.");
앗 그렇네 수정할게!

2024-07-24 15:24 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +    }
한번 고민해서 바꿔봤는데 확인 부탁함니당

2024-07-25 04:42 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        }
``` java
 try {
            leagueTeam.deleteLogoImageUrl();
            s3Service.deleteFile(getKeyOfImageUrl(keyOfImageUrl));
        } catch (Exception e) {
            s3Service.rollbackFile(keyOfImageUrl); <- 여기서 실패한다면?
            leagueTeam.rollbackLogoImageUrl(logoImageUrl); <- 여기서도 실패한다면?
            throw new CustomException(HttpStatus.INTERNAL_SERVER_ERROR, "로고 이미지 삭제에 실패했습니다.");
        }

```

이미지 삭제 자체를 트랜잭션 내부에서 처리하면 계속해서 저런 부분이 늘어날 것 같아. catch 블럭의 첫 번째 구문에서 예외가 터진다면 이미지 파일 롤백도 안됐는데 leagueTeam은 롤백이 되면서 없는 파일의 url을 들고 있게 되겠지.

내가 도출하고 싶었던 해결 법은 "트랜잭션이 끝나고 이미지 파일을 지운다"야. 사실 문제가 되는 지점은 "s3에 지워진 파일 url을 LeagueTeam이 들고 있는 경우" 이거든. 없는 url을 들고 있는 상황이 버그니까.

반면 DB에서 url을 지웠는데 s3에 해당 url이 남아있는 경우엔 s3에 잉여 데이터가 남아있긴 하지만 우리 서비스는 아무 문제가 없지. 사용자 입장에선 이미지를 지운건 똑같기 때문에 말이지.

즉 DB에서 해당 url을 지우고 트랜잭션을 커밋 + 트랜잭션 밖에서 s3 이미지를 지우기를 하면 문제를 해결할 수 있을거야. 이런 트랜잭션이 실패해도, 트랜잭션 밖에서 이미지 삭제에 실패해도 사용자 입장에선 문제될 것이 없지

2024-07-25 05:07 UTC, fingersdanny commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        }
첨언하자면, 사실 결국에는 트랜잭션 밖에서 이미지 삭제에 실패하더라도 S3에서 언젠가는 지워야하는데.. 이미 그 순간부터는 여기 로직에서 해결할 수 있는 부분이 아닌거 같아!

> "트랜잭션이 끝나고 이미지 파일을 지운다"

여기서 동규가 생각하는 걸 이벤트 기반으로 리팩토링할 수도 있을거 같은데 어떻게 생각해? @Jin409

2024-07-25 21:49 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        }
아하 그렇네.. 무슨 말인지 이해했어
DB에서 해당 url을 지우고 트랜잭션을 커밋한 뒤에 이벤트를 발행해서 s3 에서 이미지를 지우게 해볼겟

2024-07-26 11:17 UTC, ldk980130 approved these changes
수고했어! 이벤트에 관해서 다음에 더 자세히 얘기 나눠보는걸로 하자. 머지해도 될 것 같아~

2024-07-26 11:17 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        eventPublisher.publishEvent(new LogoImageDeletedEvent(getKeyOfImageUrl(logoImageUrl)));
엔티티가 `AbstractAggregateRoot` 상속 받고 있어서 내부에서 도메인 이벤트를 던질 수 있어! 그래서 `logoimageurl`을 서비스단에서 getter로 빼와도 되지 않아도 이벤트를 발행할 수 있어. 그럼 서비스 로직은 단순히 LeagueTeam이 로고를 지우는 것만 남길 수 있어.

``` java
    public void deleteLogoImage(Long leagueId, Member manager, Long teamId) {
        getLeagueAndCheckPermission(leagueId, manager);

        LeagueTeam leagueTeam = entityUtils.getEntity(teamId, LeagueTeam.class);

        leagueTeam.deleteLogoImageUrl(); // 내부에서 이벤트 발행
        leagueTeamRepository.save(leagueTeam) // AbstractAggregateRoot로 발행하는 이벤트는 jpa 리포지터리로 save가 필요
}
```

도메인 내부에서 이벤트 발행은 Report 엔티티를 한 번 참고해봐!

이벤트를 발행할 때 어떤 이름의 이벤트를 발행하냐에 대해서도 이것저것 얘기 나누고 싶지만 이 PR 리뷰가 너무 길어질 것 같으니 다음 기회에...

2024-07-26 11:17 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LogoImageEventHandler.java
> +    private final S3Service s3Service;
이거시도 다른 얘기이긴한데 S3 같은 외부 인프라를 쓰는 코드는 infrastructure 패키지에 두는 편이 좋긴 할 것 같아. infra가 다른 패키지를 의존할 순 있어도 다른 코어 로직을 담당하는 패키지들이 infra 패키지를 의존 못하게 해야하거든. 이것도 다음 기회에 더 얘기할 수 있으면 해보는걸루

2024-07-26 11:51 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        eventPublisher.publishEvent(new LogoImageDeletedEvent(getKeyOfImageUrl(logoImageUrl)));
아핫 도메인 이벤트는 새로 엔티티를 생성할 때만 가능한 줄 알고 그렇게 안했던건데 다시 생각해보니 deleteLogoImageUrl 메서드 내부에서 이벤트를 등록했음 됐던거구나
이건 수정해서 올려둘게!

2024-07-26 11:57 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        eventPublisher.publishEvent(new LogoImageDeletedEvent(getKeyOfImageUrl(logoImageUrl)));
아 맞다 이걸 이렇게 안했던 이유를 얘기해보고 싶었는데..
지금 replacePrefix 를 기준으로 잘라서 파일의 key 만 전달하고 있는데 replacePrefix 를 @Value 로 주입받으려고 하니 엔티티에서는 불가능해서 서비스에서 해주고 있거든!
그래서 이벤트 발행도 서비스에서 하고 있는데 이거에 대해서는 어떻게 생각해?

2024-07-26 11:57 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/application/LogoImageEventHandler.java
> +    private final S3Service s3Service;
오홋 오케이 이건 옮겨둘게!

2024-07-26 13:04 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        eventPublisher.publishEvent(new LogoImageDeletedEvent(getKeyOfImageUrl(logoImageUrl)));
LogoImageEventHandler도 스프링 빈인데 replacePrefix를 주입받을 수 있으니까 기존 이미지 url을 이벤트에 담아 전달하기만 해도 도메인 내부에서 충분히 발행할 수 있지 않아?

2024-07-26 13:08 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +        eventPublisher.publishEvent(new LogoImageDeletedEvent(getKeyOfImageUrl(logoImageUrl)));
앗 그렇네 ㅋㅋ 생각이 짧았다
이것까지 반영하고 머지할게!

2024-07-26 13:08 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +import com.sports.server.command.leagueteam.infrastructure.LogoImageDeletedEvent;
LogoImageDeletedEvent는 infra에 가면 안되지. application 패키지가 infra를 의존해버리니까

2024-07-26 13:09 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +import com.sports.server.command.leagueteam.infrastructure.LogoImageDeletedEvent;
단순하게 생각해서 다른 패키지들은 infrastructure 패키지의 클래스를 import 안되게끔 하면 돼!

2024-07-26 21:53 UTC, merged