[FEAT] 리그팀 삭제
hufscheer/spectator-server pull request #177
Opened 2024-07-30 07:38 UTC by Jin409

## 🌍 이슈 번호
- closed #173 

## 📝 구현 내용
- 리그팀 삭제
   - 리그팀 로고 이미지 삭제

2024-07-30 14:17 UTC, ldk980130 requested changes

2024-07-30 14:17 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamPlayerFixtureRepository.java
> +}
`Optional<Void>`는 무엇인가요...?

2024-07-30 14:17 UTC, ldk980130 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +    }
EntityUtils를 안 쓴 이유가 있나요?

2024-07-31 01:40 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamPlayerFixtureRepository.java
> +}
어머나

2024-07-31 03:31 UTC, fingersdanny reviewed
동규가 코멘트 남긴거만 처리하면 나는 괜찮은거 같아

2024-07-31 03:58 UTC, Jin409 commented on src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java
> +    }
update 할 때 페치 조인 하려고 만들었던 메서드라 사용했는데 생각해보니 삭제할 때는 필요 없을 것 같아서 entityUtils 로 바꿀게!

2024-07-31 04:05 UTC, merged