[FEAT] 게임 등록 기능 구현
hufscheer/spectator-server pull request #187
Opened 2024-08-07 06:46 UTC by Jin409

## 🌍 이슈 번호
- closed #183 

## 📝 구현 내용
- 게임 등록

## 🍀 확인해야 할 부분
### 스포츠 관련
- 스포츠를 축구에 한정 짓기로 했기에, Sports 테이블에서 '축구'를 찾아 넣도록 구현했습니다.

### 테스트 관련
- 건드려야 할 엔티티가 많아 잘 구현됐는지 확신이 안 서네용.. 서비스 테스트 유심히 한번 봐주세요!

2024-08-07 13:55 UTC, ldk980130 requested changes

2024-08-07 13:55 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +        game.addTeam(gameTeam2);
GameService 레벨에선 GameTeam 없는 Game이 만들어질 순 없지만 도메인 레벨에선 GameTeam 없는 Game이 만들어질 수 있는 구조야.

만약 Game의 생성 테스트를 작성한다면 addTeam을 호출하지 않는 한 GameTeam이 없는 Game이 만들어질 수 있는데 사실 2개의 GameTeam이 Game의 핵심이라고 생각되는데 한 번에 생성되지 않아도 되는걸까?

그렇다면 선수는 Game이 만들어질 때 한 번에 받아야 하는걸지 또 생각해보면 너무 많은 값을 생성자에서 받아야하니 나도 고민이긴 한 것 같아.

어디까지 생성자에서 받고, 어디까지는 add 메서드 등으로 후에 인풋 받는게 맞는걸까?

2024-08-07 13:55 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +                .forEach(gameTeam::registerLineup);
이건 스타일차이일 수 잇는데 LineupPlayer를 밖에서 만드는 것이 아닌, GameTeam 내부에서 만들면 어떨까? LineupPlayer가 만들어질 때 기본값이 후보라는 등의 정보를 GameService에선 캡슐화시킬 수 있을 것 같아서

``` java
public void registerLineup(LeagueTeamPlayer player) {
  LineupPlayer lineupPlayer =    new LineupPlayer(
                        gameTeam, 
                        player.getId(), 
                        player.getName(),
                         player.getNumber(), 
                        false,
                        LineupPlayerState.CANDIDATE));

  this.players.add(lineupPlayer);
}
```

2024-08-07 13:55 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +        saveGameTeamsAndCopyPlayers(requestDto, game);
되도록이면 하나의 메서드에선 한가지 일만 하도록 하면 좋을 것 같아!

2024-08-07 13:55 UTC, ldk980130 commented on src/test/java/com/sports/server/command/game/application/GameServiceTest.java
> +    @Transactional
여기 테스트에만 트랜잭셔널을 건 이유가 있을까?

2024-08-07 13:55 UTC, ldk980130 commented on src/test/java/com/sports/server/command/game/application/GameServiceTest.java
> +    }
여기도 assertJ를 쓰도록 바꾸면 좋을 것 같아~

2024-08-07 15:10 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +                .forEach(gameTeam::registerLineup);
나도 이게 더 좋은 것 같아! 수정할겡

2024-08-08 05:05 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +        saveGameTeamsAndCopyPlayers(requestDto, game);
이거 수정해봤는데 이렇게 하면 좋을지 확신이 안서서 한번 확인해주면 좋을 것 같아!

2024-08-08 06:11 UTC, Jin409 commented on src/test/java/com/sports/server/command/game/application/GameServiceTest.java
> +    @Transactional
트랜잭셔널을 걸지 않으면

```java
private void assertLineupPlayers(List<GameTeam> gameTeams) {
        for (GameTeam gameTeam : gameTeams) {
            LeagueTeam leagueTeam = gameTeam.getLeagueTeam();
            leagueTeamPlayerFixtureRepository.findByLeagueTeam(leagueTeam);
            List<Long> expectedPlayerIds = leagueTeam.getLeagueTeamPlayers().stream() // 여기!
                    .map(LeagueTeamPlayer::getId).toList();
            List<Long> actualPlayerIds = gameTeam.getLineupPlayers().stream()
                    .map(LineupPlayer::getLeagueTeamPlayerId).toList();
            assertEquals(expectedPlayerIds, actualPlayerIds, "라인업 선수 ID가 일치하지 않습니다.");
        }
    }

```

위에 표시한 부분에서 트랜잭션이 이미 닫혀버려서 세션이 없다는 오류가 나더라구. 그래서 붙였어!

2024-08-09 08:15 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +        game.addTeam(gameTeam2);
다른 기능 구현하다가 깨달았는데.. 리그 생성 >> 리그팀 생성 >> 게임 생성 (게임팀 자동 생성) 했다가 리그팀을 삭제하게 되면 연관관계 때문에 게임팀이 삭제되어야 하니까 이 경우에도 게임이 게임팀 없이 존재하게 되는데..
리그팀 삭제 되면 게임팀도 삭제하고, 게임까지 모두 삭제해버리는 게 옳으려나?

2024-08-09 15:13 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +        game.addTeam(gameTeam2);
>  GameTeam 이 생성되기 위해서는 Game 이 무조건 필요하니까 

이부분은 Game 내부에서 this 참조로 해결할 수 있을 것 같아.
``` java
GameTeam gameTeam = new GameTeam(this, team); // 실제로는 team을 여러개 받아야하지만
```

>  리그팀을 삭제하게 되면 연관관계 때문에 게임팀이 삭제되어야

이건 조금 생각해봐야할 것 같은데 지금 LeagueTeamPlayer랑 LineupPlayer가 간접참조로 되어 있는 이유가 리그팀 선수가 삭제되어도 경기에서 그 선수가 뛰었던 기록은 사라지면 안되기 때문에 그렇게 한거였잖아.

같은 맥락으로 리그팀이 삭제되었다고 해서 게임의 게임팀이 삭제되는게 맞는지 의문스럽긴 하네. 이건 정책의 문제인 것 같아.

리그팀이 삭제되면 게임에서 그 팀에 대한 정보도 사라져야 하는지? 아니면 기록의 의미로 남아야 하는지?

2024-08-09 15:15 UTC, ldk980130 commented on src/test/java/com/sports/server/command/game/application/GameServiceTest.java
> +    @Transactional
트랜잭션 밖이라서 지연로딩이 안되는거일텐데 우리가 테스트에선 Transactional을 지금까지 안쓰고 있었으니까 통일성 있게 가져가면 좋을 것 같긴해.

FixtureRepository에서 fetchjoin으로 필요한걸 다 가져오면 어떨까?

2024-08-10 03:15 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +        game.addTeam(gameTeam2);
오홍. 병룡오빠랑 논의해서 리그팀이 삭제되어도 게임팀이 삭제되지 않게 하는 게 맞는 것 같다고 확정했어!

게임팀이 리그팀을 간접 참조하도록 수정해서 올려둘게!

2024-08-10 03:28 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +        game.addTeam(gameTeam2);
리그팀 다시 생각.. 간접 참조

2024-08-10 07:26 UTC, fingersdanny reviewed
고생했어 코멘트 확인 부탁해~~

2024-08-10 08:50 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/presentation/GameController.java
> +                                                 @RequestBody @Valid CheerCountUpdateRequest cheerRequestDto) {
마즘..

2024-08-10 08:50 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/presentation/GameController.java
> +@RequestMapping
까먹었당 지울게

2024-08-12 06:02 UTC, Jin409 commented on src/test/java/com/sports/server/command/game/application/GameServiceTest.java
> +    @Transactional
사용하는 FixtureRepository 에서 LineupPlayer, LeagueTeamPlayer 를 한번에 다 가져오려고 하니까 MultipleBagFetchException 에러가 나서 아예 메서드를 분리해서 올려뒀어! 확인 부탁해

2024-08-15 06:00 UTC, fingersdanny commented on src/main/java/com/sports/server/command/game/presentation/GameController.java
> +    }
생성된 자원의 위치를 보내줘야하지 않을까?

2024-08-17 04:58 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/presentation/GameController.java
> +    }
일단 우리가 생성된 자원의 id 를 항상 반환하고 있지 않기도 하고..
동규오빠가 컨벤션에 따르기 위해서 ResponseEntity 를 이용해 작성한 TimelineController 에서 보면

```java
@PostMapping("/score")
    public ResponseEntity<Void> createScoreTimeline(@PathVariable Long gameId,
                                                    @RequestBody TimelineRequest.RegisterScore request,
                                                    Member member) {
        timelineService.register(member, gameId, request);
        return ResponseEntity.created(URI.create("")).build();
    }

```

이렇게 되어 있어서 나는 괜찮다고 판단했어. 수정하는게 나을까?

2024-08-21 06:44 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/GameService.java
> +        game.addTeam(gameTeam2);
이건 리그팀-게임팀 연관관계가 수정될 때 같이 반영되면 좋을 것 같아서 우선은 머지할게!

2024-08-21 06:51 UTC, merged