[FEAT] 리그팀에 인원수 표기하도록 수정
hufscheer/spectator-server pull request #188
Opened 2024-08-07 07:09 UTC by Jin409

## 🌍 이슈 번호
- closed #186 

## 📝 구현 내용
- 인원수를 포함해서 반환하도록 수정

2024-08-07 07:40 UTC, fingersdanny requested changes
빠른 fix 고생 많았어. 코멘트 남긴건 짚고 넘어갔으면 좋겠어!

2024-08-07 07:40 UTC, fingersdanny commented on src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
> +                () -> assertEquals(leagueTeam.sizeOfLeagueTeamPlayers(), 4)
assertEquals()에서 기대값과 실제값의 순서는 어떻게 되는지 설명해줄 수 있어?

2024-08-07 09:56 UTC, Jin409 commented on src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
> +                () -> assertEquals(leagueTeam.sizeOfLeagueTeamPlayers(), 4)
헉 이런 부분도 신경써야하는지 몰랐다.. 좋은 지적 고마워요

2024-08-07 13:29 UTC, ldk980130 commented on src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
> +                leagueTeam.getLeagueTeamPlayers().size()
사소한건데 밑에 테스트코드 보니까 `leagueTeam.sizeOfLeagueTeamPlayers()` 메서드 있던데 이거 사용하면 좋을 것 같아~

2024-08-07 13:30 UTC, ldk980130 commented on src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
> +                leagueTeam.getLeagueTeamPlayers().size()
난 병룡이형이 approve하면 머지해도 될것 같아!

2024-08-07 14:51 UTC, Jin409 commented on src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
> +                leagueTeam.getLeagueTeamPlayers().size()
테스트 코드에 있는 LeagueTeam 내부가 아니라 `leagueTeam.sizeOfLeagueTeamPlayers()` 는 `LeagueTeamResponse` 에 있는 거라서 못쓸 것 같아 ㅜ.ㅜ

2024-08-08 00:35 UTC, fingersdanny approved these changes
LGTM~ 👍🏻

2024-08-08 06:12 UTC, merged