[FEAT] 리그 삭제
hufscheer/spectator-server pull request #190
Opened 2024-08-07 15:02 UTC by Jin409

## 🌍 이슈 번호
- closed #189

## 📝 구현 내용
- 리그 삭제

## 🍀 확인해야 할 부분
- 논리 삭제를 위해 is_deleted 를 true 로 바꿨습니당

2024-08-09 08:58 UTC, fingersdanny requested changes

2024-08-09 08:58 UTC, fingersdanny commented on src/main/java/com/sports/server/command/league/domain/League.java
> +    }
이 메서드를 생각하지말고 단순히 대회 삭제 메서드 구현한다고 생각했을 때 (논리삭제와 관계 없이), 여러 번 호출 했을 때 얻어지는 결과값이 뭐라고 생각해??

2024-08-09 08:58 UTC, fingersdanny commented on src/main/java/com/sports/server/command/league/application/LeagueService.java
> +        league.delete();
논리삭제를 구현할 때 ``@SQLDelete``를 사용하지 않은 이유가 있을까?

2024-08-15 07:19 UTC, ldk980130 approved these changes
확인 완료!

2024-08-16 06:45 UTC, merged