[FEAT] 라인업 주장으로 등록 및 취소
hufscheer/spectator-server pull request #204
Opened 2024-08-14 07:18 UTC by Jin409

## 🌍 이슈 번호
- closed #203 

## 📝 구현 내용
- 라인업 주장으로 등록

## 🍀 확인해야 할 부분
### 도메인 테스트
도메인 테스트를 어디서 해야 할지 모르겠어서 진입점인 GameTest 에 추가했는데 적절하다고 생각되는지 궁금합니다!

### 주장 등록 및 취소 한번에
```java
public void changeCaptainStatus(LineupPlayer lineupPlayer) {
        Optional<LineupPlayer> captain = this.lineupPlayers.stream()
                .filter(LineupPlayer::isCaptain)
                .findAny();

        boolean playerExistsInTeam = this.lineupPlayers.stream()
                .anyMatch(lp -> lp.equals(lineupPlayer));

        if (captain.isPresent() && !captain.get().equals(lineupPlayer) && playerExistsInTeam) {
            throw new IllegalStateException("주장은 두 명 이상 등록할 수 없습니다.");
        }

        if (playerExistsInTeam) {
            lineupPlayer.changeCaptainStatus();
        }
    }
```

게임팀에 위와 같이 주장이 존재하고, 요청을 보낸 라인업 선수와는 일치하지 않고 (일치하는 경우에는 주장을 취소하는 요청일 것이기 때문에), 라인업 선수가 해당 팀이라면 예외를 던지도록 했습니다.
이 코드의 가독성을 조금 더 향상할 수 있는 방법이 없을까요?

2024-08-15 07:49 UTC, ldk980130 requested changes

2024-08-15 07:49 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        game.changeCaptainStatus(lineupPlayer);
메서드 이름으로 `game.appointCaptain()`은 어떨까? 도메인에 더 어울리는 이름으로 생각해보면 좋을 것 같아! changeXXStatus는 너무 개발용어 같달까

2024-08-15 07:49 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/domain/Game.java
> +    }
클라이언트에게서 `gameTeamId`까지 함께 받아온다면 어느 팀에 어느 선수를 주장으로 변경할지 명확해져서 메서드가 더 단순해질 것 같은데 어떨까?

2024-08-15 07:49 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/domain/GameTeam.java
> +
이 메서드도 클라이언트에게서 gameTeamId도 받아온다면 이 선수가 자신의 팀 선수가 아니면 바로 예외를 터뜨리면 되니까 구현이 더 단순해질 것 같아.

2024-08-17 06:32 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/Game.java
> +    }
좋아! 이 방향으로 수정해볼게

2024-08-17 07:42 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        game.changeCaptainStatus(lineupPlayer);
appointCaptain 을 사용하고 다시 코드를 읽어봤는데 조금 어색하다는 생각이 들었어.
왜냐하면 이 메서드로 주장을 등록하기도 하고 해제하기도 하는데, appoint 는 등록의 의미만 있는 것 같아서!
챗지피티는 toggleCaptain 을 얘기하고.. 나는 changeCaptain 이런 식이면 어떨까 싶은데 어때?

2024-08-17 10:05 UTC, fingersdanny approved these changes

2024-08-18 10:00 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        game.changeCaptainStatus(lineupPlayer);
한 api에서 주장 등록, 취소를 지금 상태에 따라 분기하는 로직인가? 

이런 멱등하지 않은 로직은 안좋을 수 있는게 클라이언트가 api 따닥을 못막는 경우가 더러 있단 말이야. 그럼 주장을 등록하려 했지만 뒤따라 온 api 호출이 다시 취소해 버릴 수도 있어서 가능하면 멱등하게 로직을 설계하면 어떨까?

2024-08-18 11:05 UTC, fingersdanny commented on src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
> +    }
그냥 false로 바꾸지 않는 이유가 있을까?

이러면 내부 동작을 예측하기가 힘들거 같다는 생각이 있어

2024-08-18 11:09 UTC, fingersdanny reviewed
고생 많았어~ 코멘트 남긴거 같이 얘기해보자

2024-08-18 11:09 UTC, fingersdanny commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        LineupPlayer lineupPlayer = findLineupPlayer(gameTeam, lineupPlayerId);
gameTeam 찾을 때는 메서드 안에서 Exception 던지게 하고 LineupPlayer를 찾을때는 다른 메서드로 분리한 이유가 있을까?

2024-08-20 07:57 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        game.changeCaptainStatus(lineupPlayer);
흠.. 그렇겠다
이거 반영해서 다시 수정해볼게!

2024-08-20 07:57 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
> +    }
위에 코멘트 남긴 것처럼 이 메서드로 주장을 등록하기도 하고 해제하기도 해서 이렇게 설계했어!
근데 동규오빠 피드백처럼 멱등하지 못하다는 생각이 들어서 이건 다시 수정해볼겟

2024-08-20 07:59 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        LineupPlayer lineupPlayer = findLineupPlayer(gameTeam, lineupPlayerId);
gameTeam 은 단순히 해당 객체가 존재하는지 아이디로 찾는 거라 메서드로 굳이 분리하지 않아도 된다고 생각했어. 그런데 LineupPlayer 는 해당 객체가 존재하는지 + 해당 팀에 속하는 플레이어가 맞는지 두가지 판단을 해야 해서 메서드로 분리하는 게 낫겠다고 판단했어!

2024-09-09 07:26 UTC, Jin409 commented
api 분리해서 다시 할 것!

2024-09-09 07:26 UTC, closed without merging