[FEAT] 게임 진행 상태 변경 타임라인 기능 추가
hufscheer/spectator-server pull request #209
Opened 2024-08-18 15:16 UTC by ldk980130

## 🌍 이슈 번호
- #206 
  - 아직 구현이 끝나지 않아 닫지 않음

## 📝 구현 내용
- 게임 진행 상태 변경 타임라인 api 추가
- 타임라인 조회에서 조회되도록 dto 수정

## 🍀 확인해야 할 부분
### 타임라인 생성에 따라 경기를 제어하는 로직을 별도 메서드로 분리
- 기존에는 Timeline 생성자 내부에서 Game 상태 변경도 함께 수행
- 생성자 중간에 Game 관련 로직이 섞여 있으니 코드가 명확히 보이지 않았기에 별도 메서드로 분리
- 서비스 계층에서 메서드를 호출해 Game에 영향을 주도록 리팩터링

``` java
    public void register(Member member, Long gameId, TimelineRequest request) {
        Game game = checkPermissionAndGet(gameId, member);

        Timeline timeline = timelineMapper.toEntity(game, request);
        timeline.apply();

        timelineRepository.save(timeline);
    }
```

### 게임 상태 변경 타임라인이 Game을 제어하는 로직 고민
- Quarter를 다음 Quarter로 변경하고, 삭제될 때는 이전 Quarter로 변경해야 하는데 현재 데이터 구조로는 불가능
- Quarter에 순서 필드를 추가하여 Quarter 간 정렬될 수 있도록 만든 뒤 어떤 상태 변경이냐에 따라 game의 Quarter를 변경하도록 구현할 예정

2024-08-28 07:02 UTC, Jin409 approved these changes
수고하셨어용

2024-09-11 03:46 UTC, fingersdanny requested changes
고생했어~~ 코멘트 남긴거 같이 봐보자

2024-09-11 03:46 UTC, fingersdanny commented on src/main/java/com/sports/server/command/timeline/application/TimelineMapper.java
>          }
타임라인 종류가 더 늘어난다면 else if를 계속 추가하는 방향으로 작성해야할까?

2024-09-11 03:46 UTC, fingersdanny commented on src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java
> +
아직 구현이 덜 되어서 method body가 비어있는걸까?

2024-09-11 03:46 UTC, fingersdanny commented on src/main/java/com/sports/server/command/timeline/dto/TimelineRequest.java
>      }
``gameTeamId``를 상속받는 객체의 생성자로 옮긴 이유가 있어??

2024-09-11 03:46 UTC, fingersdanny commented on src/main/java/com/sports/server/query/dto/response/RecordResponse.java
난 Timeline 성격 상 그리고 현재 구조 상으로 라인업선수, 게임팀, 리그팀은 사실 상 timeline에서 not null 이어야 하다고 생각하는데

아래 클래스 내부에 Optional을 활용한 이유를 설명해줄 수 있을까?

2024-09-12 13:50 UTC, ldk980130 commented on src/main/java/com/sports/server/command/timeline/dto/TimelineRequest.java
>      }
게임 상태 변경 타임라인의 경우에는 gameTeamId가 필요가 없어서 부모 클래스에 올리기가 애매하더라고

2024-09-12 13:52 UTC, ldk980130 commented on src/main/java/com/sports/server/query/dto/response/RecordResponse.java
이것도 상태 변경 타임라인 때문인데 얘가 좀 성격이 달라서 나도 좀 고민이야. 상태 변경은 전반전 시작, 후반전 시작, 이런 타임라인이라서 사실 선수도, 팀도 필요가 없어. 형 말을 듣고 보니 얘는 타임라인에서 제외를 해야하나 싶기도 하고..

2024-09-12 13:53 UTC, ldk980130 commented on src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java
> +
아직 이 시점에는 교체 타임라인 시에 적용할 부분이 없어서 비워두었어. 승희가 작업하고 있는 [출전 선수 정보 변경](https://github.com/hufscheer/spectator-server/pull/214)에서 여길 채우게 될 것 같아

2024-09-12 13:55 UTC, ldk980130 commented on src/main/java/com/sports/server/command/timeline/application/TimelineMapper.java
>          }
TimelineService 같은 곳에서는 다형성을 잘 활용했다고 생각했는데 결국 각각 다른 JSON 응답을 내려줘야 하는 API의 끝단에서는 결국 분기 코드가 들어가게 되긴 하더라고. 좀 더 고민해볼게!

2024-09-14 12:02 UTC, ldk980130 commented on src/main/java/com/sports/server/query/dto/response/RecordResponse.java
@fingersdanny 
일단 아래처럼  `TimelineSupplier`라는 함수형 인터페이스를 두고 Map으로 타입별 분기를 수행시키는 방식으로 리팩터링했어. 이제 새로운 타입이 추가되면 private 함수 추가, Map에 값 추가만 해주면 toEntity 메서드는 변경하지 않아도 돼.

private 메서드를 외부의 다른 클래스로 추출할 수도 있을 것 같은데 TimelineMapper 내부에 매핑 로직을 모아두고 싶어서 일단 아래처럼 구현했어

``` java
@RequiredArgsConstructor
public class TimelineMapper {
    private final EntityUtils entityUtils;

    private final Map<TimelineType, TimelineSupplier> suppliers = Map.of(
            TimelineType.SCORE, (g, r) -> toScoreTimeline(g, (TimelineRequest.RegisterScore) r),
            TimelineType.REPLACEMENT, (g, r) -> toReplacementTimeline(g, (TimelineRequest.RegisterReplacement) r),
            TimelineType.GAME_PROGRESS, (g, r) -> toProgressTimeline(g, (TimelineRequest.RegisterProgress) r)
    );

    public Timeline toEntity(Game game, TimelineRequest request) {
        return Optional.ofNullable(suppliers.get(request.getType()))
                .map(supplier -> supplier.get(game, request))
                .orElseThrow(() -> new IllegalArgumentException("지원하지 않는 타입입니다."));
    }

    private ScoreTimeline toScoreTimeline(Game game,
                                          TimelineRequest.RegisterScore scoreRequest) {
        return ScoreTimeline.score(
                game,
                getQuarter(scoreRequest.getRecordedQuarterId()),
                scoreRequest.getRecordedAt(),
                getPlayer(scoreRequest.getScoreLineupPlayerId())
        );
    }

// ...
```

2024-09-15 15:29 UTC, fingersdanny commented on src/main/java/com/sports/server/query/dto/response/RecordResponse.java
사실 다른 클래스로 빼는거 보다는 TimelineType이 추가되었으니까 외부의 다른 클래스를 쓰지 않고 Map을 쓰지 않고 Enum Type의 멤버 변수로 TimelineSupplier를 옮기는 방법도 있어.

Supplier를 직접 구현하지 않고 java.util에 있는 BiFunction 같은걸 사용하면 BiFunction 인터페이스 내부 메서드인 apply를 통해서 Timeline객체를 만드는 로직도 넘겨줄 수 있겠지.

내가 말한 방식대로 하면 또 다른 클래스를 만들지 않아도 되고 매핑 로직도 각 Enum 객체가 들고 있는 형태로 구현될거 같은데 어떻게 생각해?

2024-09-15 15:31 UTC, fingersdanny reviewed
고생했어~ TimelineType을 추가한건 좋은거 같아. 코멘트에 남긴 내용만 이야기 해보면 좋을거 같아

2024-09-15 15:33 UTC, fingersdanny commented on src/main/java/com/sports/server/query/dto/response/RecordResponse.java
> 이것도 상태 변경 타임라인 때문인데 얘가 좀 성격이 달라서 나도 좀 고민이야. 상태 변경은 전반전 시작, 후반전 시작, 이런 타임라인이라서 사실 선수도, 팀도 필요가 없어. 형 말을 듣고 보니 얘는 타임라인에서 제외를 해야하나 싶기도 하고..

확실히 그렇긴 하네... 근데 상태 변경 타임라인이 없다면 다른 타임라인과 유기적으로 하나의 타임라인을 구성하는 것처럼 보여줄 수 있는 방법이 있을까?

2024-09-16 05:10 UTC, ldk980130 commented on src/main/java/com/sports/server/query/dto/response/RecordResponse.java
@fingersdanny 
> Enum 객체가 들고 있는 형태로 구현될거 같은데 어떻게 생각해?

나도 Enum으로 분기하는 코드는 좋아하긴 하는데 매핑 로직을 넣기는 애매한게 있어.
`TimelineType`은 도메인이고, `TimelineRequest`는 DTO인데 DTO를 도메인이 의존하게 할 순 없어서 말이야.

> 근데 상태 변경 타임라인이 없다면 다른 타임라인과 유기적으로 하나의 타임라인을 구성하는 것처럼 보여줄 수 있는 방법이 있을까?

없지...ㅋㅋㅋㅋ 그래서 일단은 지금처럼 가야할 것 같아.

2024-09-18 09:14 UTC, fingersdanny approved these changes

2024-09-18 09:44 UTC, merged