Feat/#203 captain
hufscheer/spectator-server pull request #211
Opened 2024-09-10 11:49 UTC by Jin409

## 🌍 이슈 번호

## 📝 구현 내용

## 🍀 확인해야 할 부분

2024-09-10 13:51 UTC, fingersdanny requested changes
고생 많았어~ 코멘트 남긴거 대부분은 질문이고 테스트 쪽은 조금 얘기해보면 좋을 거 같아.

2024-09-10 13:51 UTC, fingersdanny commented on src/test/java/com/sports/server/command/game/domain/GameTest.java
> +    }
여기는 왜 ``@Nested``를 사용했어?

2024-09-10 13:51 UTC, fingersdanny commented on src/test/java/com/sports/server/command/game/domain/GameTeamTest.java
> +    }
``@Nested``는 계층적 테스트를 적거나 비슷한 테스트들을 모으는데 사용하는데 위처럼 작성한 이유가 있을까?
* https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested
* https://johngrib.github.io/wiki/junit5-nested/

2024-09-10 13:51 UTC, fingersdanny commented on src/test/java/com/sports/server/command/game/acceptance/GameAcceptanceTest.java
>          AssertionsForClassTypes.assertThat(response.statusCode()).isEqualTo(HttpStatus.CREATED.value());
그...승희가 적은건 아닌거 아는데 이것도 AssertJ로 바꿔줄 수 있어?

2024-09-10 13:51 UTC, fingersdanny commented on src/main/java/com/sports/server/command/game/domain/Game.java
> +            throw new IllegalArgumentException("해당 게임팀은 이 게임에 포함되지 않습니다.");
이 파일을 제일 마지막에 봐서 그런데 이쯤되니 의도적인 ``IllegalArgumentException``사용인가 싶은...

2024-09-12 00:08 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
> +            throw new IllegalArgumentException("해당 선수는 주장이 아닙니다.");
앗 이거 임시로 IllegalArgumentException 로 해두고 올리기 전에 고치려고 했는데 까먹었다 ㅜ..ㅜ 고쳐서 다시 푸쉬할게!

2024-09-12 00:09 UTC, Jin409 commented on src/test/java/com/sports/server/command/game/domain/GameTest.java
> +    }
주장 상태를 변경하는 경우에 대한 도메인 테스트가 늘어날거라고 생각해서 처음에 @Nested 로 했는데 적다보니 여러개가 아니게 돼서 이건 수정해둘게!

2024-09-12 02:05 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
> +            throw new IllegalArgumentException("해당 선수는 주장이 아닙니다.");
흠 근데 이거 나는 IllegalArgumentException 도 괜찮다구 생각하는데 오빠는 CustomException 을 써야한다고 생각하는 이유가 궁금해

2024-09-12 02:15 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
> +            throw new IllegalArgumentException("해당 선수는 주장이 아닙니다.");
고민하다가 IllegalArgumentException 도 괜찮겠다 싶었는데.. 상태 코드가 400인게 나을 것 같아서 수정했어!

2024-09-12 04:02 UTC, fingersdanny approved these changes
LGTM~

2024-09-12 04:41 UTC, merged