Feat/#219 reported cheertalks
hufscheer/spectator-server pull request #221
Opened 2024-09-18 07:44 UTC by Jin409

## 🌍 이슈 번호

## 📝 구현 내용

## 🍀 확인해야 할 부분

2024-09-18 09:56 UTC, ldk980130 requested changes
수고했어!

2024-09-18 09:56 UTC, ldk980130 commented on src/main/java/com/sports/server/query/presentation/CheerTalkQueryController.java
> +    public ResponseEntity<List<ReportedCheerTalkResponse>> getAllReportedCheerTalks(@PathVariable final Long leagueId,
이 기능은 '신고'가 핵심일까 '응원톡'이 핵심일까?

만약 신고라는 맥락과 상관 없이 어떤 리그의 모든 응원톡을 조회하는 api가 생긴다면 url path는 어떻게 정하면 좋을까?

응원톡의 입장에서는 '신고'라는 개념을 모르니까 '신고된 응원톡'이락 하면 '신고'를 중심 및 대상으로 로직을 짜야하지 않을까 싶어서 말이야. (신고가 응원톡을 참조하고 있으니)

근데 이걸 고치려면 대공사일 것 같아서 고치지 않아도 될 것 같은데 적어도 '신고된 응원톡을 조회'한다는 맥락을 담아서 url path를 고치면 어떨까? url만 보면 신고랑 상관없이 리그의 모든 응원톡을 조회하는 것 같아

2024-09-18 09:56 UTC, ldk980130 commented on src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepositoryImpl.java
> +                        .where(booleanBuilder.build()),
booleanBuilder에 아무것도 넣지 않는데 생성한 이유가 있을까?

2024-09-18 09:56 UTC, ldk980130 commented on src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepositoryImpl.java
> +                        .where(booleanBuilder.build()),
여기서도 booleanBuilder를 아무것도 넣지 않고 사용하고 있는데 사용하지 않는다면 굳이 사용하지 않아도 돼.

DynamicBooleanBuilder는 null의 위험이 있는 값을 깔끔하게 다루고 싶어서 만든 유틸성 클래스야. null일 위험이 없는 조건엔 굳이 안써도 되고 if(x == null) 조건문을 써야할 것 같을 때 쓰면 좋을 것 같아!

``` java
.where(DynamicBooleanBuilder.builder()
                        .and(() -> league.startAt.year().eq(year)) // year이 null일 수도 있어서 사용
                        .build())
```

2024-09-19 02:53 UTC, Jin409 commented on src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepositoryImpl.java
> +                        .where(booleanBuilder.build()),
앗 이거 챗지피티로 리팩토링 했더니 놓쳤네... ㅎㅋ
근데 지금 cursor 가 null 이면 CheerTalkDynamicRepositoryImpl.getCursorCreatedAt() 에서 대응이 되고, size 가 null 이면 PageRequestDto 에서 대응이 되거든!

```java
public record PageRequestDto(
        Long cursor,
        Integer size
) {
    private static final Integer DEFAULT_SIZE = 10;

    @Override
    public Integer size() {
        if (size == null) {
            return DEFAULT_SIZE;
        }

        return size;
    }
}
```

그래서 굳이 BooleanBuilder 를 안써도 될 것 같은데 오빠 생각은 어때?

2024-09-19 02:54 UTC, Jin409 commented on src/main/java/com/sports/server/query/presentation/CheerTalkQueryController.java
> +    public ResponseEntity<List<ReportedCheerTalkResponse>> getAllReportedCheerTalks(@PathVariable final Long leagueId,
무슨 말인지 이해했어! 

@GetMapping("/leagues/{leagueId}/cheer-talks/reported")
@GetMapping("/leagues/{leagueId}/reported-cheer-talks")

이 둘 중에 하나는 어떨까/

2024-09-19 10:28 UTC, Jin409 commented on src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepositoryImpl.java
> +                        .where(booleanBuilder.build()),
추가적으로.. 기존에 존재하는 CheerTalkResponse 와 여기서 사용하는 ReportedCheerTalkResponse 를 합치고 싶은데 어때?

```java
public class CheerTalkResponse {
    public record ForSpectator(
            Long cheerTalkId,
            String content,
            Long gameTeamId,
            LocalDateTime createdAt,
            Boolean isBlocked
    ) {
        public ForSpectator(CheerTalk cheerTalk) {
            this(
                    cheerTalk.getId(),
                    checkCheerTalkIsBlocked(cheerTalk),
                    cheerTalk.getGameTeamId(),
                    cheerTalk.getCreatedAt(),
                    cheerTalk.isBlocked()
            );
        }

        private static String checkCheerTalkIsBlocked(CheerTalk cheerTalk) {
            if (cheerTalk.isBlocked()) {
                return null;
            }
            return cheerTalk.getContent();
        }
    }

}

```

예를 들어 ForManager, Reported 이런 식으로 추가해 나가면서 외부에서 
CheerTalkResponse.Reported / CheerTalkResponse.ForManager 이렇게 사용할 수 있도록 하고 싶어!

2024-09-19 10:29 UTC, Jin409 commented on src/main/java/com/sports/server/query/presentation/CheerTalkQueryController.java
> +    public ResponseEntity<List<ReportedCheerTalkResponse>> getAllReportedCheerTalks(@PathVariable final Long leagueId,
바로 이 다음 이슈가 리그에 해당하는 전체 응원톡 조회라 딱 오빠가 우려하는 상황이 발생하네..
선견지명이었다

2024-09-21 05:53 UTC, ldk980130 commented on src/main/java/com/sports/server/query/presentation/CheerTalkQueryController.java
> +    public ResponseEntity<List<ReportedCheerTalkResponse>> getAllReportedCheerTalks(@PathVariable final Long leagueId,
개인적으로는 전자가 나은 것 같아~ @GetMapping("/leagues/{leagueId}/cheer-talks/reported")

2024-09-21 06:00 UTC, ldk980130 commented on src/main/java/com/sports/server/query/repository/CheerTalkDynamicRepositoryImpl.java
> +                        .where(booleanBuilder.build()),
합친다는게 Request들처럼 상속 구조로 가져간다는거지? 좋은 것 같아~

query 패키지 내부아 레이어드도 되어 있고, dto 패키지 내부에 클래스가 너무 많아졌는데 그렇게 해서 파일 수를 줄일 수 있을지도 모르겠네

2024-09-21 08:08 UTC, merged