[FEAT] 신고 시 욕설 확인 기능 구현
hufscheer/spectator-server pull request #228
Opened 2024-09-21 06:54 UTC by Jin409

## 🌍 이슈 번호
- closed #224

## 📝 구현 내용
- 기존에 파이썬으로 구현됐던 람다 서버의 신고 기능을 내부 로직으로 변경
   - 추후 람다로 이전할 계획이기에 기존의 메서드들을 남겨둠

## 🍀 확인해야 할 부분

2024-09-21 07:46 UTC, ldk980130 requested changes

2024-09-21 07:46 UTC, ldk980130 commented on src/main/java/com/sports/server/command/report/infrastructure/ReportEventHandler.java
> +    private final ReportProcessor reportProcessor;
어차피 나중에 다시 람다 서버를 쓰게 되면서 기존 `FeignClient`를 쓰는 `ReportCheckClient`로 변경할 예정인거지?

그거와 별개로 `ReportEventHandler`의 내부 코드를 전혀 건드리지 않으면서 이번 PR을 마무리하는 방법을 썼으면 더 좋았을 것 같은데 이건 한 번 고민해보길~

2024-09-21 07:46 UTC, ldk980130 commented on src/main/java/com/sports/server/common/application/TextFileProcessor.java
> +        ClassPathResource resource = new ClassPathResource(fileName);
`IOException`을 외부로 던지지 말고 여기서 언체크 예외로 전환해서 던지면 어떨까?

`TextFileProcessor`가 예외를 던짐으로써 `ReportEventHandler`까지 예외가 전파되고 있어.  

`ReportEventHandler`를 비롯한 다른 클라이언트 신고 처리를 파일 IO로 하든, 외부 api를 쓰든 전혀 관심사가 아니기 때문에 외부로 던지지 않으면 좋을 것 같아!

2024-09-21 07:46 UTC, ldk980130 commented on src/main/java/com/sports/server/command/report/application/ReportProcessor.java
> +            cheerTalk.block();
'신고를 하면 응원톡이 블락된다' 라는 정책이 있고, `Report` 내부에 `CheerTalk`이 있으니까 `Report` 내부에서 block을 처리하면 어떨까?

2024-09-21 08:03 UTC, Jin409 commented on src/main/java/com/sports/server/command/report/infrastructure/ReportEventHandler.java
> +    private final ReportProcessor reportProcessor;
맞아!
ReportCheckClient  인터페이스 설계와는 별개로 ReportEventHandler 의 내부 코드를 건드리지 않고 신고 기능을 구현할 수 있었던 걸까?! 나는 건드리지 않는 방법이 떠오르지 않는데 어떤 방식을 생각했던 건지 물어봐도 될까?

2024-09-21 08:23 UTC, ldk980130 commented on src/main/java/com/sports/server/command/report/infrastructure/ReportEventHandler.java
> +    private final ReportProcessor reportProcessor;
`ReportCheckClient` 인터페이스가 지금은 HTTP 요청을 한다는 거를 `ResponseEntity`를 반환하고 있어서 지금은 코드 변경이 필연적일 수밖에 없어.

그런데 만약 인터페이스를 HTTP 의존적이지 않게 짰다면 `ReportCheckClient`를 `ReportProcesor`가 구현하게 하면 핸들러는 `ReportCheckClient`를 의존한 코드 그대로 사용할 수 있었겠지.

그래서 이번참에 신고 처리 인터페이스를 제네럴하게 구현해서 ReportEventHandler가 걔를 의존하게 하고, 그 인터페이스 구현체를 '람다 서버 이용하는 구현체', '내부 파일 이용하는 구현체'로 다르게 구현할 수 있을 것 같은데 리팩터링해보면 어떨까?

2024-09-21 08:30 UTC, Jin409 commented on src/main/java/com/sports/server/command/report/infrastructure/ReportEventHandler.java
> +    private final ReportProcessor reportProcessor;
아하 그렇겠다 무슨 말인지 이해했어! 
이거까지 적용해서 수정해볼게

2024-09-22 07:45 UTC, Jin409 commented on src/main/java/com/sports/server/command/report/infrastructure/ReportEventHandler.java
> +    private final ReportProcessor reportProcessor;
추후 리팩토링 하기!

2024-09-22 07:47 UTC, merged