Feat/#218 cheertalks
hufscheer/spectator-server pull request #232
Opened 2024-09-22 07:44 UTC by Jin409

## 🌍 이슈 번호

## 📝 구현 내용

## 🍀 확인해야 할 부분

2024-09-22 08:14 UTC, fingersdanny reviewed
고생했어유~ 코멘트를 확인해줘~

2024-09-22 08:14 UTC, fingersdanny commented on src/main/java/com/sports/server/query/application/CheerTalkQueryService.java
>  }
이러면 그냥 checkPermission을 어디 Validator에 밀어 넣는게 낫지 않을까?? 너무 많은 곳에서 쓰이고 있는데 매번 반복해서 작성해야하니...

2024-09-22 08:14 UTC, fingersdanny commented on src/main/java/com/sports/server/query/dto/response/CheerTalkResponse.java
>                      game.getId(),
내가 이거 Blocked로 해서 새로 만들었는데... 흠 어떻게 통일 시키는게 좋으려나? 아니면 내가 만든 dto는 그대로 둬도 되나

2024-09-22 08:46 UTC, Jin409 commented on src/main/java/com/sports/server/query/application/CheerTalkQueryService.java
>  }
추가 완 👍🏻

2024-09-24 16:15 UTC, fingersdanny requested changes
고생 많았어! 코멘트 남긴건 짚고 넘어가는게 좋을거 같아

2024-09-24 16:15 UTC, fingersdanny commented on src/main/java/com/sports/server/common/application/PermissionValidator.java
먼저 ``ManagedEntity`` interface를 통해서 구현한건 좋은 접근 방법인거 같아.

그런데 Class 명이 ``PermissionValidator``인데 권한 검사외에 너무 많은 일을 하고 있는거 같다고 생각해. 

검사해야하는 Entity들을 Service 단에서 조회해서 인자로 받고 권한만 검사하게 두는 방식은 어떻게 생각해?? 그럼 Component로 등록하지 않아도 될거야.

2024-09-25 00:28 UTC, Jin409 commented on src/main/java/com/sports/server/common/application/PermissionValidator.java
좋아! 이렇게 수정해볼게

2024-09-25 03:30 UTC, fingersdanny requested changes
Validator 다시 한번 확인해보면 좋을 거 같아

2024-09-25 03:30 UTC, fingersdanny commented on src/main/java/com/sports/server/common/application/PermissionValidator.java
현재 코드에서는 ``@Service``안써도 되지 않을까?? 내가 모르는 Bean으로 등록하고 싶은 다른 이유가 있는 걸까?

2024-09-25 03:30 UTC, fingersdanny commented on src/main/java/com/sports/server/common/application/PermissionValidator.java
어떤 호출 경로에서 발생한 예외인지 알 수 있도록 그리고 메시지가 좀 더 명시적이면 좋을거 같아

2024-09-25 03:30 UTC, fingersdanny commented on src/main/java/com/sports/server/command/game/application/GameService.java
>                  .forEach(gameTeam2::registerLineup);
코드 내용과는 별개로... [Collection.forEach와 Stream.forEach의 차이](https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/)

2024-09-26 05:02 UTC, Jin409 commented on src/main/java/com/sports/server/common/application/PermissionValidator.java
PermissionValidator 가 의존성 주입이 필요하지 않고, 동일한 작업을 반복하기에 오빠 말대로 정적 메서드로 선언하는 게 나을 것 같아 수정했어! 👍🏻

2024-09-26 05:46 UTC, merged