[FEAT] 가려진 응원톡 전체 조회하기
hufscheer/spectator-server pull request #235
Opened 2024-09-22 08:05 UTC by fingersdanny

## 🌍 이슈 번호
* close #195 

## 📝 구현 내용
* 가려진 응원톡을 대회 별로 조회

## 🍀 확인해야 할 부분
* cheer-talk-fixture.sql 에만 john@example.com으로 되어 있길래 이것도 john.doe@example.com으로 수정했어
* 근데 configureMockJwt()를 ``@BeforeEach`` 같은걸로 몰아줄 수는 없을려나.. 매번 치는게 번거롭네

2024-09-25 03:32 UTC, hodadako commented
@ldk980130 어차피 시간 내기 힘들어보이긴 하지만 아직 미구현된 부분들이 있어서 리뷰 시작하지 않아도 좋아. 

#232 완료되고 응답 형식이랑 ``Validator`` 클래스 추가하면 내가 그때 다시 알려줄게

2024-09-26 05:51 UTC, Zena0128 requested changes
댓글 하나만 확인해주세요!!

2024-09-26 05:51 UTC, Zena0128 commented on src/main/java/com/sports/server/auth/config/SecurityConfig.java
> +                                mvc.pattern(HttpMethod.POST, "/leagues/{leagueId}/cheer-talks/blocked"),
요거 POST아니고 GET 아닌가용?-?

2024-09-26 07:48 UTC, fingersdanny commented on src/main/java/com/sports/server/auth/config/SecurityConfig.java
> +                                mvc.pattern(HttpMethod.POST, "/leagues/{leagueId}/cheer-talks/blocked"),
당연하게도 GET이 맞습니다..~@ 수정할게요.

2024-09-29 09:07 UTC, Zena0128 approved these changes
확인 완료했슴당 고생하셨습미다

2024-09-29 10:44 UTC, merged