[FEAT] 신고된 응원톡 가리기/가리기 해제 기능
hufscheer/spectator-server pull request #238
Opened 2024-09-23 05:45 UTC by Zena0128

## 🌍 이슈 번호
- #231 

## 📝 구현 내용
- 신고된 응원톡을 가리거나 가리기 해제하는 기능 추가

## 🍀 확인해야 할 부분
- 인수 테스트의 경우 가려진 응원톡 전체조회, 응원톡 전체조회 기능 머지 후 추가할 예정입니당

2024-09-23 07:02 UTC, Jin409 requested changes
수고하셨습니당~

2024-09-23 07:02 UTC, Jin409 commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
> +            throw new CustomException(HttpStatus.BAD_REQUEST, CheerTalkErrorMessages.CHEER_TALK_ALREADY_BLOCKED);
이미 가려진 응원톡에 대해 다시 가리고자 요청을 보내도 예외를 던지지 않아도 되지 않을까요?
하나의 응원톡에 대해 여러번 차단 요청을 보내면 첫번째에는 아무 응답이 없고 두번째부터는 예외를 던지니 멱등성이 깨질 것 같습니다!
여러번 차단 요청이 온다고 해도 내부적으로 유니크해야 하거나 버그가 아니니 예외가 던져지지 않아도 될 것 같다는 생각이 드네용

++ unblock 도 반대로 마찬가지라는 생각이 드네요

2024-09-23 07:03 UTC, Jin409 commented on src/main/java/com/sports/server/command/cheertalk/presentation/CheerTalkController.java
> +    @PatchMapping("/cheer-talks/{leagueId}/{cheerTalkId}/block")
++ SecurityConfig 에 엔드포인트 등록해야 할 것 같습니당

2024-09-23 09:16 UTC, Zena0128 commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
> +        checkPermission(leagueId, manager);
오 안그래도 자주 쓰이는 함수라 분리해두면 좋을 것 같았는데 감사합미당
pr 머지 후 수정하겠슴당!

2024-09-23 09:37 UTC, Zena0128 commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
> +            throw new CustomException(HttpStatus.BAD_REQUEST, CheerTalkErrorMessages.CHEER_TALK_ALREADY_BLOCKED);
아하 저는 처음엔 단순히 이미 block/unblock 상태인 응원톡 객체에 계속 update 쿼리를 날리는 게 비효율적이라고 생각해서 예외를 던지게 한 건데
예외를 던지는 것보단 block 상태 체크 후 이미 가려졌거나 가리기 해제된 상태면 패스하는 식으로 가는 게 더 좋겠네요!

2024-09-24 00:40 UTC, Jin409 commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
> +            throw new CustomException(HttpStatus.BAD_REQUEST, CheerTalkErrorMessages.CHEER_TALK_ALREADY_BLOCKED);
굳굳 좋은 것 같습니다!!

2024-09-24 04:03 UTC, fingersdanny requested changes
고생 많으셨어요.💯 리뷰 남긴거 확인하시고 코멘트 남겨주세요.

2024-09-24 12:29 UTC, Zena0128 commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
> +            throw new CustomException(HttpStatus.BAD_REQUEST, CheerTalkErrorMessages.CHEER_TALK_ALREADY_BLOCKED);
@fingersdanny 헛 hibernate는 dirty checking을 거치기 때문에 flush 직전 상태가 처음 상태와 동일할 시 불필요한 쿼리가 나가지 않는군요..! 첨 알았어요 감사합니다!

2024-09-24 12:51 UTC, Zena0128 commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
> +    }
제가 "응원톡 가리기/가리기 해제 시 무조건 신고객체가 존재한다 + 신고 상태를 검증해야 한다"고 이해했던 상태에서 짠 코드였는데
신고 객체가 아예 존재하지 않는 상태에서도 가리기/가리기 해제가 가능해서 해당 메소드들은 필요가 없어져 현재 삭제한 상태입니다!

다만 2에서 말씀주신 부분처럼 앞으로는 하나의 메서드에서 두 가지 역할을 할 때는 최대한 중복 지양하기 위해서 코드 짜보도록 하겠습니다 감사합니다 🫡

2024-09-24 12:56 UTC, Zena0128 commented on src/test/java/com/sports/server/command/cheertalk/application/CheerTalkServiceTest.java
> +    }
해당 부분도 이미 가려진/가리기 취소된 응원톡에 대해서 예외처리를 하지 않기로 해서 삭제했습니다!

2024-09-25 01:03 UTC, Jin409 commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
> +        cheerTalk.block();
왜 cheerTalk.block 을 Report.updateToValid 에도 존재하고 이 코드에도 존재하도록 짜신건지 궁금하네용

2024-09-25 03:19 UTC, fingersdanny reviewed
제가 남긴건 그렇게 중요한건 아닌거 같아서 승희가 코멘트 남긴 것만 전반적으로 수정하면 좋을 것 같아요

2024-09-25 03:19 UTC, fingersdanny commented on src/test/java/com/sports/server/command/cheertalk/acceptance/CheerTalkAcceptanceTest.java
> +        // 가려진 응원톡 전체조회 기능 머지 후 테스트 추가 예정
todo로 남기는게 좋아보여요

```suggestion
        //todo : 가려진 응원톡 전체조회 기능 머지 후 테스트 추가 예정
```

2024-09-25 03:19 UTC, fingersdanny commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
승희가 남긴대로 #232 머지되면 전반적으로 수정하면 될 것 같네요

2024-09-25 03:19 UTC, fingersdanny commented on src/docs/asciidoc/api.adoc
> +=== 가려진 응원톡을 가리기 취소하기
지금 구현대로라면.. 가려지지 않은 응원톡도 가리기 취소할 수 있지 않나요? ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-09-25 08:45 UTC, Zena0128 commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
> +        cheerTalk.block();
아 그거 Report.updateToValid에서 제외하려다가 #228 에서 사용되길래 그냥 중복으로 두었어요,,!  
신고객체가 있으면 updateToValid에서 block되고, 없으면 cheerTalk에서 block되도록 둔 건데 
그냥 if else문 사용해서 한 번만 블락되도록 짜는 게 좋을까용?

2024-09-25 08:57 UTC, Zena0128 commented on src/docs/asciidoc/api.adoc
> +=== 가려진 응원톡을 가리기 취소하기
앗 구러네여 문서 수정하겠슴다.

2024-09-25 09:25 UTC, Jin409 commented on src/main/java/com/sports/server/command/cheertalk/application/CheerTalkService.java
> +        cheerTalk.block();
넵넵 optional 의 present 메서드를 사용하는 게 좋아 보이네요!

2024-09-25 11:12 UTC, Jin409 commented on src/main/java/com/sports/server/command/report/domain/Report.java
> +        cheerTalk.unblock();
유효하지 않은 신고로 전환할 때 응원톡은 가려지지 않은 상태일거예요!
그래서 unblock 메서드는 호출하지 않아도 될 것 같습니다.
피그마 확인하시면 가려진 응원톡들은 가려진 응원톡 탭에 따로 모아져 있고, 거기에는 신고당한 응원톡들은 없을겁니당!

2024-09-25 11:20 UTC, Jin409 commented on src/main/java/com/sports/server/command/report/domain/Report.java
> +        cheerTalk.unblock();
정책을 다시 한번 정리해보자면...

신고가 되면 응원톡이 바로 가려지는 것이 아님.
신고가 유효하다고 판단되면 가려짐

여기에서 신고가 유효하다고 판단되는 경우는 두개
- 내부 로직이 판단
- PENDING 상태인 신고를 보고 매니저가 판단

가려지지 않은 상태에서 가린 것을 해제하는 경우는 하나
- 가려진 응원톡 목록 화면에서 확인

그래서 신고가 무효하다고 해서 반드시 unblock 를 해야 하는 것은 아니기에 빼도 될 ㅓㄱㅅ 같습니다!
저도 헷갈려서 말이 복잡한데.. 이해 안되시면 추후에 구두로 다시 얘기 나눠보면 좋을 것 같습니다! @.@

2024-09-25 11:25 UTC, Zena0128 commented on src/main/java/com/sports/server/command/report/domain/Report.java
> +        cheerTalk.unblock();
앗 이부분은 신고 무효가 아니라 응원톡 가리기 취소할 때 사용하는 부분이라 unblock하게 해뒀어요!! 신고 무효하는 함수는 #239 에서 report.cancel() 메소드 따로 만들었긴 한데,,
updateToInvalid 함수를 신고 무효, 응원톡 가리기 취소에서 공통으로 사용하고 unblock은 따로 하는 게 좋으려나용,,?

2024-09-25 11:58 UTC, fingersdanny approved these changes

2024-09-26 00:35 UTC, Jin409 commented on src/main/java/com/sports/server/command/report/domain/Report.java
> +        cheerTalk.unblock();
따로 대화해서 해결 완~

2024-09-27 12:55 UTC, merged