[FEAT] 응원톡 신고 무효처리 기능
hufscheer/spectator-server pull request #241
Opened 2024-09-23 09:15 UTC by Zena0128

## 🌍 이슈 번호
- #239 

## 📝 구현 내용
- 응원톡 신고를 무효처리하는 기능

## 🍀 확인해야 할 부분
- 신고 대기 상태가 아닌 응원톡 신고 무효처리 시도하면 던지는 예외는 앞선 pr 머지된 후 끌어다 쓸 예정

2024-09-24 13:34 UTC, Zena0128 commented on src/main/java/com/sports/server/command/report/application/ReportService.java
> +        }
이미 무효  처리된 신고가 다시 무효처리돼도 큰 상관이 없어서 이 부분 빼버릴까 합니다!

2024-09-25 00:25 UTC, Jin409 requested changes
수고하셨어요~!

2024-09-25 00:25 UTC, Jin409 commented on src/main/java/com/sports/server/command/report/application/ReportService.java
> +        }
넵 저는 이거 빼도 될 것 같아요!

2024-09-25 00:25 UTC, Jin409 commented on src/test/resources/report-fixture.sql
> +       (4, '2023-11-11 00:00:00', '신고대기중인 댓글이야', false, 1);
PENDING 이 신고 대기중이라기보다는 신고 됐고 + 신고 내부의 로직 자체로는 유효하지 않다고 판단됐지만 + 매니저의 확인을 기다리고 있는 신고니까 이거 고쳐보는 게 어떨까요?

2024-09-26 00:34 UTC, Jin409 approved these changes

2024-09-27 13:40 UTC, merged