[FIX] 주장으로 등록된 후보를 선발로 변경 시 주장 해제되도록 수정
hufscheer/spectator-server pull request #259
Opened 2024-09-29 12:41 UTC by Zena0128

## 🌍 이슈 번호
- #258 

## 📝 구현 내용
- 주장으로 등록된 후보를 선발로 변경 시 주장 해제되도록 수정
- 선발/후보로 변경하는 부분에서도 게임팀id 파라미터로 받도록 수정
- 게임 인수테스트에서 제대로 테스트되고 있지 않던 부분 수정
`() -> assertThat(actual.get(0).id().equals(lineupPlayerId))`
=> `() -> assertThat(actual.get(0).id()).isEqualTo(lineupPlayerId)`

## 🍀 확인해야 할 부분
- 급한 건 아닌데.. LineUpPlayer의 state, isCaptain을 수정하는 로직들이 굳이 Game을 거쳐야 하는지? 로직은 GameTeam, LineUpPlayer만 사용해서 구현하면 안 되는지??

2024-09-29 13:40 UTC, ldk980130 requested changes
수고하셨습니다! 수정하면 좋을 것들에 대해 코멘트 남겨 두었습니다.

> 급한 건 아닌데.. LineUpPlayer의 state, isCaptain을 수정하는 로직들이 굳이 Game을 거쳐야 하는지? 로직은 GameTeam, LineUpPlayer만 사용해서 구현하면 안 되는지??

이 질문에 대해 답변 드리자면 Game을 하나의 '일관성을 지키는 단위'로서 보고있기 때문입니다. (이를 도메인 주도 디자인에서는 애그리거트 루트라고 부릅니다)

GameTeam과 LineupPlayer는 Game의 서브 엔티티로서 다뤄지는데요, 이러한 서브 엔티티들의 일관성을 지키는 주체로서 Game이 해야할 일이 있습니다.

예를 들어 `하나의 게임엔 2개의 게임팀만 존재할 수 있다`라는 요구사항이 있다면 어떨까요? Game을 거치지 않고 gameTeamRepository.save(gameTeam)으로 만들어릴 수도 있겠지만 Game을 통해서 로직을 구현하는 편이 캡슐화, 일관성을 지키는 차원에선 더 편하다고 생각해요. 그리고 만약 게임팀이 동시에 만들어질 수도 있는 상황에선 Game을 중심으로 동시성을 제어할 수도 있겠죠.

LineupPlayer도 마찬가지에요. 일단 지금 그러한 검증 로직이 있는지는 모르겠는데 사실 팀에는 주장이 한 명만 있어야 하잖아요? 이러한 검증도 LineupPlayer가 단순히 자신의 상태를 바꾸게 되면 일관성이 깨질 위험이 있어요.

그런데 GameTeam에게 LineupPlayer를 넘기면 그러한 일관성 로직을 잘 지킬 수 있게 됩니다. 그런데 GameTeam도 Game의 서브엔티티이니 LineupPlayer도 Game이 관리하도록 만들어버린겁니다. LineupPlayer가 다뤄질 때 Game까지 확장해서 일관성을 확인해야할 로직이 있을 수도 있으니까요.

Game을 거치지 않고 각각의 서브엔티티들이 로직을 수행하기 시작하면 Game 단위로 지켜져야할 일관성의 로직이 서비스 레이어에 노출되게 됩니다. 그래도 큰 문제는 없겠지만 테스트를 짤 때 도메인 테스트라는 편한 길을 두고 서비스 테스트를 더 많이해야할 수도 있게 돼요.

2024-09-29 13:40 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +    public void changePlayerStateToStarter(final Long gameId, final Long gameTeamId, final Long lineupPlayerId) {
LineupPlayer 내부에 GameTeam이 있으니까 추가적으로 파라미터로 받을 필요는 없지 않을까요?

2024-09-29 13:40 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        game.registerStarter(gameTeam, lineupPlayer);
이것도 마찬가지로 사실 lineupPlayer가 자신이 무슨 팀인지를 알고 있으니 받을 필요가 없지 않을까 생각해요.

linupPlayer 하나만 받는다면 game == lineupPlayer.gateTeam.game만 검증하면 되지만 gameTeam도 받게되면 game과 gameTema.game 그리고 lineupPlayer.gameTeam과 gameTeam 등 검증해야할게 너무 늘어난다고 생각합니다.

2024-09-29 13:40 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/domain/Game.java
> +        gameTeam.registerStarter(lineupPlayer);
한 번 더 강조하자면 GameTeam과 LineupPlayer를 함께 받게 되면 검증해야할게 늘어납니다.

GameTeam의 Game, LineupPlayer의 Game, 그리고 이 메서드가 존재하는 Game 자신까지 3개의 Game이 서로 같다는걸 합의해야합니다.

LineupPlayer만 받는다면 Game과 LineupPlayer가 서로 정합성이 맞는지만 확인하면 돼요

2024-09-29 13:40 UTC, ldk980130 commented on src/main/java/com/sports/server/command/game/domain/GameTeam.java
> +                    if (lp.isCaptain()) {lp.revokeCaptainFromPlayer();}
changeStateToCandidate 메서드 내부에 로직을 다 넣으면 어떨까요?

LineupPlayer 자신이 주장인지 아닌지 본인이 알고 있으니까 주장을 내리고 말고 하는 걸 바깥에 노출하지 않아도 된다고 생각해요. 

'후보로 내려갈 때 주장이었다면 주장도 아니게 된다'라는 로직의 책임을 LineupPlayer가 지게 되면 GameTeam 코드는 전혀 안고치고 로직을 수정할 수 있어 응집도는 높아지고 결합은 떨어지게 되지 않을까요?

``` java
        this.lineupPlayers.stream()
                .filter(lp -> lp.equals(lineupPlayer))
                .findAny()
                .ifPresent(LineupPlayer::changeStateToCandidate); // 내부에서 주장이었다면 주장을 해제하는 로직이 있음
```

2024-09-29 14:53 UTC, Zena0128 commented on src/main/java/com/sports/server/command/game/domain/Game.java
> +        gameTeam.registerStarter(lineupPlayer);
아 오오 말씀해주신 것들 다 잘 이해했습니다 !! game>gameTeam>lineUpPlayer의 관계이니 game, lineUpPlayer끼리만 확인하면 된다는 말씀이시져!
해당 내용들 반영해서 다시 푸시했습니다 감사합니다 🫡

2024-09-30 01:24 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        game.registerStarter(lineupPlayer.getGameTeam(), lineupPlayer);
이렇게 되면 결국 게임팀을 인자로 받게 되기 때문에 동규오빠가 이야기했던 피드백이 반영되지 않는 것 같습니다..!
```java
game.registerStarter(lineupPlayer);
```
```java
public class Game{
  public void registerStarter(final LineupPlayer lineupPlayer) {
        this.teams.forEach(gameTeam -> gameTeam.registerStarter(lineupPlayer));
    }
}
```

이런식으로 하면 게임팀 필요 없이 라인업플레이어만으로도 로직을 수행할 수 있습니다..!

제 생각에 가장 처음 코드에서

```java
   public void changeStateToCandidate() {
        if (this.state == CANDIDATE) {
            throw new CustomException(HttpStatus.BAD_REQUEST, "이미 후보로 등록된 선수입니다.");
        }
        this.state = CANDIDATE;
        deactivatePlayerInGame();
    }
```
이 메서드에 주장에서 해제하는 메서드만 중간에 끼워넣으면 될 것 같습니다..!

2024-09-30 01:57 UTC, Zena0128 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        game.registerStarter(lineupPlayer.getGameTeam(), lineupPlayer);
움 일단 제가 처음의 코드를 변경한 이유는 
1. 처음의 코드는 자신이 어느 팀에 소속된 상태인지 이미 정보를 갖고 있는, 한 명의 플레이어의 상태를 변경하는데 두 팀 모두의 LineUpPlayer를 돌면서 찾아야 하기 때문에
변경하고자 하는 플레이어의 게임팀만 돌면서 찾으면 좋지 않을까 => Game.registerStarter에서 해당 선수의 GameTeam을 뽑아내서 그 팀에 대해서만 돌도록 수정
2. 선수를 선발/후보로 변경할 때에도 해당 Game의 GameTeam에 속한 선수인지 검증해야 하지 않을끼? => validateGameTeam 메소드 사용하도록 추가

라고 생각해서 코드를 수정하긴 했습니다..! 

그리고 동규님이 말씀해주신 부분을 저는 `어차피 LineUpPlayer는 자신의 GameTeam을 알고 있으니 따로 GameTeamId를 받는 건 불필요하다` + `game == lineupPlayer.gameTeam.game은 검증해야 한다`
요렇게 이해했어서
Game과 LineUpPlayer의 정합성을 확인하려면 LineUpPlayer의 GameTeam이 해당 Game에 속해있는지 검증해야 된다고 이해해서 요렇게 짠 건데 요 부분은 어떻게 생각하시나요,,?!

2024-09-30 02:41 UTC, Zena0128 commented on src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
> +        game.registerStarter(lineupPlayer.getGameTeam(), lineupPlayer);
game의 메소드 파라미터로 gameteam을 받지 않도록 수정해서 푸시했습니당!

2024-09-30 02:48 UTC, merged