[FEAT] 경기 종료 이후 새로운 타임라인 등록 막기
hufscheer/spectator-server pull request #276
Opened 2024-10-01 01:01 UTC by Zena0128

## 🌍 이슈 번호
- closed #271 

## 📝 구현 내용
- Game의 state가 FINISHED일 때 새로운 타임라인 등록 시도 시 에러 발생

## 🍀 확인해야 할 부분

2024-10-01 01:21 UTC, Jin409 requested changes

2024-10-01 01:21 UTC, Jin409 commented on src/main/java/com/sports/server/command/timeline/application/TimelineService.java
> +        if (game.getState().equals(GameState.FINISHED)) {
GameState 도 Game 에 완전히 엮여 있기도 하고, 내부적으로도 로직을 숨길 수 있으니
validateGameStateForTimeline 이런 식으로 Game 내부에 메서드로 옮기는 것은 어떨까요?

2024-10-01 01:22 UTC, Jin409 commented on src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
> +                .isInstanceOf(CustomException.class);
메시지도 검증하면 더 좋을 것 같네요~!

2024-10-01 01:59 UTC, Jin409 commented on src/main/java/com/sports/server/command/game/domain/Game.java
> +    public void checkFinished() {
저는 메서드명이 조금 애매한 것 같기는 한데.. checkFinished 면 뭔가 boolean 을 반환하고 finshed 인지 아닌지 확인만 하는 느낌이에요!!
만약 저희가 `끝난 게임에 대해 득점한 선수들의 랭킹을 1씩 올린다` 라는 로직을 추가할 때 checkFinished 라는 메서드를 쓰게 되지 않으려나요? 그 상황에서는 예외를 던지면 안되는데 메서드명만으로는 그걸 판단할 수가 없어서 애매해질 것 같아요! 한번 더 고민해보심 더 좋을 것 같습니당.

2024-10-01 03:40 UTC, Jin409 approved these changes

2024-10-03 01:40 UTC, fingersdanny reviewed
크게 변경해야할 부분은 없는거 같아요. 고생하셨습니다.

2024-10-03 01:40 UTC, fingersdanny commented on src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
> +                .hasMessage("종료된 게임에 새로운 타임라인을 등록할 수 없습니다.");
메시지도 하드코딩하는 거보단 원본에 있는 TimelineErrorMessage를 활용해보면 좋을거 같아요.

2024-10-03 01:40 UTC, fingersdanny commented on src/main/java/com/sports/server/command/game/domain/Game.java
> +        if (this.getState().equals(GameState.FINISHED)) {
state가 null인 경우는 떠오르지 않지만 객체의 동등성 비교를 할때 ``Objects.equals()``를 사용하면 NPE를 방지할 수 있어요

2024-10-06 10:00 UTC, Zena0128 commented on src/main/java/com/sports/server/command/game/domain/Game.java
> +        if (this.getState().equals(GameState.FINISHED)) {
NPE도 항상 고려해야겠군요! 
근데 game의 state가 nullable=false로 되어 있어서.. 요 경우는 enum equals를 그대로 사용해도 될까요?-?

2024-10-06 10:31 UTC, merged