[FEAT] 라인업 조회 시 선발/후보 선수로 나눠서 조회
hufscheer/spectator-server pull request #284
Opened 2024-10-07 08:01 UTC by Zena0128

## 🌍 이슈 번호
- closed #283

## 📝 구현 내용
- 라인업 조회할 때 선발(InGamePlayers), 후보(CandidatePlayers)로 나눠서 조회하도록 변경

## 🍀 확인해야 할 부분

2024-10-07 09:53 UTC, Jin409 requested changes
수고하셨습니다~

2024-10-07 09:53 UTC, Jin409 commented on src/main/java/com/sports/server/query/dto/response/LineupPlayerResponseSeparated.java
> +public record LineupPlayerResponseSeparated(
`LineupPlayerResponse.Seperated` 가 될 수 있도록 옮기는 건 어떻게 생각하시나요?

2024-10-07 09:53 UTC, Jin409 commented on src/main/java/com/sports/server/query/dto/response/LineupPlayerResponseSeparated.java
> +	List<PlayerResponse> inGamePlayers,
starter 과 candidate 라는 명칭을 사용하고 있는데 `inGame` 이라는 용어를 사용하신 이유가 있을까용?

2024-10-07 10:48 UTC, Zena0128 commented on src/main/java/com/sports/server/query/dto/response/LineupPlayerResponseSeparated.java
> +public record LineupPlayerResponseSeparated(
LineupPlayerResponse를 클래스로 바꾸고 거기 안에서 기존 LineupPlayerResponse(기존; 출전 중인 선수만 리턴)랑 Separated(출전 중, 후보 선수 나눠 리턴)을 레코드로 관리하는 방식 말씀하시는 건가용?

2024-10-07 10:49 UTC, Zena0128 commented on src/main/java/com/sports/server/query/dto/response/LineupPlayerResponseSeparated.java
> +	List<PlayerResponse> inGamePlayers,
안그래도 나중에 말씀드리려고 메모해뒀었는데
선발/후보로 나누기보다는 출전/후보로 나누는 게 좀 더 명확하지 않나 싶어서요!
왜냐면 후보이다가 교체돼서 출전 선수로 나가게 되면 starter(선발)은 아니니까.. 추후에 starter->inGame으로 변경하면 좋을 것 같다고 생각하고 있었습미다

2024-10-07 11:21 UTC, fingersdanny requested changes

2024-10-07 11:21 UTC, fingersdanny commented on src/main/java/com/sports/server/query/dto/response/LineupPlayerResponseSeparated.java
> +	List<PlayerResponse> inGamePlayers,
정책이 바뀐건지는 모르겠는데 선발/후보와 출전/후보는 아예 다른 개념으로 생각하기로 했던거 같아요 @Jin409

2024-10-07 11:21 UTC, fingersdanny commented on src/main/java/com/sports/server/query/application/LineupPlayerQueryService.java
선발 후보를 아래처럼 나누지 말고 queryParam 같은걸 받아서 동적으로 조회하게 하는게 낫지 않을까요? (QueryDSL 사용)

2024-10-07 11:21 UTC, fingersdanny commented on src/main/java/com/sports/server/query/application/LineupPlayerQueryService.java
지금은 나누어서 조회한다고 하셨는데 사실 이건 나누어서 조회하는게 아니라 응답 안에 나누어져있는 구현 같아요. 조회를 선수의 선발/후보 상태로 해야한다면 아래처럼 하나의 응답에서 나누어 보내주는게 아니라 API를 두 번 호출하게 하는게 맞지 않을까요?

2024-10-07 11:21 UTC, fingersdanny commented on src/main/java/com/sports/server/query/dto/response/LineupPlayerResponseSeparated.java
> +	}
선발 후보 기능을 분리하지 않아서 생긴 첫번째 문제점이라고 생각해요. 위 구현대로면 inGamePlayer와 candidatePlayer가 바뀌어 들어가도 동작하니까요. 그러면 API를 사용하는 사람 입장에서는 동일하게 화면을 구현했는데 후보 자리에는 선발 선수가 들어오는 경우가 생길거 같네요.

2024-10-08 03:59 UTC, Zena0128 commented on src/main/java/com/sports/server/query/application/LineupPlayerQueryService.java
움 프론트측에서 라인업페이지에서 사용할 api를 
현재 : gameTeamPlayers에 STARTER, CANDIDATE 상관 없이 묶어서 보냄
요구사항 : 선발, 후보 묶음으로 나눠서 보내달라
이렇게 변경해달라고 한 거라 하나의 api 안에서 응답으로 나누는 걸로도 충분할 거라고 생각했어여 ! 어차피 하나의 페이지 안에서 쓰이는거라,,,?.?

2024-10-08 04:16 UTC, Zena0128 commented on src/main/java/com/sports/server/query/dto/response/LineupPlayerResponseSeparated.java
> +	List<PlayerResponse> inGamePlayers,
제가 잘못 이해한 부분이 있어서 inGamePlayer -> StarterPlayer로 변경하도록 하겠슴다

2024-10-08 04:27 UTC, Zena0128 commented on src/main/java/com/sports/server/query/dto/response/LineupPlayerResponseSeparated.java
> +	}
엄 근데 해당 api가 단순히 특정 게임의 라인업 조회 api라,, 직접 db에서 특정 게임의 라인업 플레이어들 갖고와서->state가 STARTER, CANDIDATE인지에 따라 filter해서 집어넣는 거라 
이미 서비스단에서 필터링 후에 집어넣어서 inGamePlayer와 candidatePlayer가 바뀌어서 들어갈 일이 없지 않을까.. 라고 생각하긴 했어요

근데 말씀 듣고 보니 서비스단에서는 라인업 선수들 그냥 한 번에 받고 response단에서 필터링하는 게 좀 더 명확하려나,,? 하는 생각이 들긴 하네여

2024-10-08 05:32 UTC, Jin409 approved these changes

2024-10-08 06:37 UTC, merged